### ISSUE TITLE
build.gradle 引入后发现不是最新的代码

### ISSUE THREAD

**Issue by likun123687** [YummyLau/PanelSwitchHelper#1]
build.gradle 源上不是最新的吗？希望更新下

**Comment by YummyLau** [comment]
你指的是支持popup的代码吗？目前sample里面有，不过库还没升。

**Comment by likun123687** [comment]
多谢回复，我指的是支持popup代码。

**Comment by YummyLau** [comment]
@likun123687 嗯嗯好，本来这部分功能还没有打算开放，如果不急周末我会拉feature分支，测试完之后统一更新。后续feature分支处理。之前的不规范临时提交请见谅。
