### ISSUE TITLE
软键盘弹出后，再按返回键无法退出，sample也有这个bug

### ISSUE THREAD

**Issue by caihuanjian** [YummyLau/PanelSwitchHelper#10]
@Override
    public void onBackPressed() {
        if (mHelper != null && mHelper.hookSystemBackForHindPanel()) {
            return;
        }
        super.onBackPressed();
    }

hookSystemBackForHindPanel一直返回true

**Comment by caihuanjian** [comment]
软键盘出现的时候，按返回键，onBackPressed是不会调的老哥。这个时候你的
currentPanelId 一直等于 PANEL_KEYBOARD

**Comment by YummyLau** [comment]
> 软键盘出现的时候，按返回键，onBackPressed是不会调的老哥。这个时候你的
> currentPanelId 一直等于 PANEL_KEYBOARD

软件盘出现的时候，onBackPressed被系统拦截，系统自己隐藏输入法。hookSystemBackForHindPanel 是用来处理隐藏面板的，没办法退出指的是？

**Comment by YummyLau** [comment]
> 软键盘出现的时候，按返回键，onBackPressed是不会调的老哥。这个时候你的
> currentPanelId 一直等于 PANEL_KEYBOARD
嗯已知bug，正在修复。

**Comment by YummyLau** [comment]
> 软键盘出现的时候，按返回键，onBackPressed是不会调的老哥。这个时候你的
> currentPanelId 一直等于 PANEL_KEYBOARD

感谢 @caihuanjian 反馈 1.0.3已经修复
