### ISSUE TITLE
list列表数据量多状态下，列表的动画很奇怪，不平滑

### ISSUE THREAD

**Issue by BingoDevil** [YummyLau/PanelSwitchHelper#100]
list列表数据量多状态下，列表的动画很奇怪，不平滑，看视频地址 https://maint.duofriend.com/upload/app/58060389249434/2020_0927_182021_qGPYzO.mp4

**Comment by BingoDevil** [comment]
recycleView的item会闪烁闪烁的动。没有过渡动画。

**Comment by YummyLau** [comment]
@BingoDevil 打开滑动模式。

**Comment by BingoDevil** [comment]
@YummyLau 感谢～
