### ISSUE TITLE
关于EditText不可用时无法关闭PanelView

### ISSUE THREAD

**Issue by lannaican** [YummyLau/PanelSwitchHelper#103]
场景: 在禁言时EditText设为不可用，这时候点击panel_trigger是正常唤起PanelView的，但是再次点击没有关闭PanelView
期望: 在EditText设为Disbale时希望再次点击triggleView可以关闭PanelView

**Comment by YummyLau** [comment]
@lannaican 可支持，下版本测试稳定之后可支持。

**Comment by YummyLau** [comment]
@lannaican 在兼容性测试过程中，这个交互被QA认定为是 “缺陷”。
暂时回退这个功能，新版本暂时不支持。因为禁言属于业务逻辑。
你可以监听 addViewClickListener 对应的 panel_trigger，然后判断当前是否是禁言且显示面板，如果当前禁言则调用reset就可以了。
