### ISSUE TITLE
小米4视频横屏状态下，布局弹出后闪一下自动关闭

### ISSUE THREAD

**Issue by JoinLi** [YummyLau/PanelSwitchHelper#104]
Androidx版本：是
PanelSwitchHelper版本：v1.3.10（目前最新版） 之前用的是v1.3.1，没有此问题
手机型号: 小米4
手机系统版本： Android 6.0.1   miui10.8.7.20体验版
问题描述：视频小窗竖屏下没问题，全屏后，点击输入弹幕，无法弹出布局（闪一下），测试目前最新版本（1.3.10）demo，也是此问题。

**Comment by JoinLi** [comment]
测试demo-扩展场景-视频播放（优于b站）

**Comment by YummyLau** [comment]
@JoinLi 小米4 10.8.9.13 兼容测试无异常。
你进一下群反馈群，提供更具体的场景及代码。

**Comment by YummyLau** [comment]
无有效反馈，暂时关闭。

**Comment by YummyLau** [comment]
@JoinLi 升级v1.3.11解决
