### ISSUE TITLE
RelativeContentContainer包裹SmartRefreshLayout出现滑动冲突

### ISSUE THREAD

**Issue by JD-CP** [YummyLau/PanelSwitchHelper#109]
Androidx版本：是
PanelSwitchHelper版本：1.3.10
手机型号: 三星note8
手机系统版本： Android 9.0
问题描述：在聊天页，有下拉加载更多聊天记录的需求，现在在RelativeContentContainer中，SmartRefreshLayout作为子view，会出现滑动异常，请问如何类似的解决滑动冲突呢？

**Comment by YummyLau** [comment]
@JD-CP 如果recyclerview外部有嵌套布局，你对应
```
           .addContentScrollMeasurer(new ContentScrollMeasurer() {
                        @Override
                        public int getScrollDistance(int defaultDistance) {
                            return defaultDistance - unfilledHeight;
                        }

                        @Override
                        public int getScrollViewId() {
                            return R.id.smart_refresh_layout;  //更改为你内嵌recyclerview的容器。
                        } 
                    })
```
需要调整成你外部嵌套的容器id。

**Comment by JD-CP** [comment]
> @JD-CP 如果recyclerview外部有嵌套布局，你对应
> 
> ```
>            .addContentScrollMeasurer(new ContentScrollMeasurer() {
>                         @Override
>                         public int getScrollDistance(int defaultDistance) {
>                             return defaultDistance - unfilledHeight;
>                         }
> 
>                         @Override
>                         public int getScrollViewId() {
>                             return R.id.smart_refresh_layout;  //更改为你内嵌recyclerview的容器。
>                         } 
>                     })
> ```
> 
> 需要调整成你外部嵌套的容器id。

谢谢 已解决 怪我没仔细看文档😭
