### ISSUE TITLE
DialogFragment出错

### ISSUE THREAD

**Issue by scatl** [YummyLau/PanelSwitchHelper#11]
是不支持dialogfragment么

java.lang.IllegalArgumentException: PanelSwitchHelper$Builder#build : not found PanelSwitchLayout by id(2131230921)
        at com.effective.android.panel.PanelSwitchHelper$Builder.build(PanelSwitchHelper.java:599)
        at com.effective.android.panel.PanelSwitchHelper$Builder.build(PanelSwitchHelper.java:621)

**Comment by YummyLau** [comment]
> dialogfragment

dialogfragment暂时没有测试，dialogFragment不应该承载这么重的功能哦。
另外，源码层级是根据activity去获取布局的，目前仅支持activity及popupwindow。
你能描述下你的场景吗？

**Comment by scatl** [comment]
场景就是在activity界面弹出一个dialogfragment进行评论回复等功能，会用到表情面板。考虑到用户体验就没有用activity了

**Comment by YummyLau** [comment]
明白，这种你可以用popupwindow，暂时提供这个。后续如果有需要我可以兼容，考虑下个版本支持下。

**Comment by YummyLau** [comment]
@EvanEvil 最新版本 1.0.4 已经支持。
