### ISSUE TITLE
键盘弹起动画卡顿

### ISSUE THREAD

**Issue by a154225859** [YummyLau/PanelSwitchHelper#110]
Androidx版本：是
PanelSwitchHelper版本：v1.3.11
手机型号: 三星S10
手机系统版本： Android 10
[在直播语聊房布局控件比较多的场景，输入法弹起上移时动画卡顿，收起下移时不卡

2020-11-16 20:48:32.404 27146-27146/in.dradhanus.liveher D/LogTracker: PanelSwitchLayout(74649917)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 2280) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2168 
    screenH (dynamic,exclude SystemUI)                 = 1182 
    localLocation[y]                                   = 0 
    toolbarH                                           = 0 
    StatusBarH                                         = 112 
    NavigationBarH                                     = 0 
    layout Location                                    = (0,0) 
    paddingTop                                         = 0 
    keyboardH                                          = 986 
    ContentContainerTop                                = -986 
    ContentContainerH                                  = 2280 
    PanelContainerTop                                  = 1294 
    PanelContainerH                                    = 986 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-986,1080,1294) 
    panelContainer Layout                              = (0,1294,1080,2280) 
2020-11-16 20:48:32.405 27146-27146/in.dradhanus.liveher D/LogTracker: PanelSwitchLayout(74649917)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 1182 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 112 
    deviceNavigationBarH                               = 0 
    systemInset                                        = left(112) top(0) right(0) bottom(986) 
    inset                                              = left(0) top(112) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 112, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 112 
    minLimitCloseKeyboardH                             = 0 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 986 
    currentKeyboardInfo                                = keyboardH : 986, realKeyboardH : 986, isShown : true 

尝试把ui移到demo里 也有卡顿的情况 可以直接替换PhoneDouyinLiveActivity的布局测试
https://raw.githubusercontent.com/a154225859/demo/main/activity_douyin_live_layout.xml

**Comment by a154225859** [comment]
https://github.com/a154225859/demo/blob/main/DB730B552BFB344E7FC25A089FD10C77.mp4
这是录屏

**Comment by YummyLau** [comment]
看了下你的布局虽然复杂，暂时框架的滑动并不会引起布你复杂布局内部的调整。这个得看你的布局及activity逻辑怎么写。
目前也有其他app的直播/语音也用了这个库，如果方便你可以上传下你的Demo这个页面的代码，我定位下，上述的log无法直观反映问题。
 @a154225859

**Comment by a154225859** [comment]
> 看了下你的布局虽然复杂，但是框架的滑动并不会引起布你复杂布局内部的调整。这个得看你的布局及activity逻辑怎么写。
> 目前也有直播/语音房间的app也用了这个库，如果方便的话，可以上传下你的Demo这个页面的代码，我定位下，上述的log无法直观反映问题。
> @a154225859

不需要其他的代码 可以直接替换我这activity_douyin_live_layout.xml 到你的demo里测试  手机直播优于抖音效果的那个界面

**Comment by YummyLau** [comment]
@a154225859 你里面80个多个布局约束，一个layout重新计算，大量消耗了cpu资源。

**Comment by YummyLau** [comment]
如无进一步反馈，issue关闭，有问题随时打开追加信息。
