### ISSUE TITLE
bilibilidemo 横屏模式下拉起键盘失效

### ISSUE THREAD

**Issue by hanggege** [YummyLau/PanelSwitchHelper#116]
oppoA9 手机 用bilibili  demo  横屏模式下拉起键盘  第一次成功 之后一直拉起就收回，麻烦看一下

**Comment by YummyLau** [comment]
@hanggege 这个问题部分Rom上Edittext inputType的效果和主流Rom不一致，已经有修复方法了，很快能升级解决。

**Comment by hanggege** [comment]
这个解决大概要多久？或者能不能告诉我有什么可以临时处理的方式，项目要上线了 现在换来不及了 哭哭哭~~~

**Comment by YummyLau** [comment]
@hanggege 下午或者你进群我给你个aar包。

**Comment by hanggege** [comment]
感谢~~，群号是什么？

**Comment by YummyLau** [comment]
@hanggege 加我微信你备注下，我拉下你

**Comment by YummyLau** [comment]
升级v1.3.12

**Comment by hanggege** [comment]
好了 感谢
