### ISSUE TITLE
使用dialog模式，键盘弹出后导致下面的布局上移，请问如何解决

### ISSUE THREAD

**Issue by WU1208** [YummyLau/PanelSwitchHelper#118]
![image](https://user-images.githubusercontent.com/13074367/100584359-f52be300-3326-11eb-8e0d-1ac489fe2434.png)

**Comment by YummyLau** [comment]
@WU1208 往上移是正常的。因为你window更改之后导致Activity原来的整体window高度也跟着变小。要固定不上移动你可以在Activity显示之后固定根View的高度就好。

**Comment by WU1208** [comment]
已解决，多谢

**Comment by Ubitar** [comment]
我这把Builder中的activity.window改成dialog.window就好了
