### ISSUE TITLE
偶现的崩溃问题。

### ISSUE THREAD

**Issue by chenyp1994** [YummyLau/PanelSwitchHelper#119]
Androidx版本：是
PanelSwitchHelper版本：v1.3.2
手机型号:  华为-honor8X Max
手机系统版本： Android 9.1.0
问题描述：偶现的崩溃问题。
Log提供：
![image](https://user-images.githubusercontent.com/12231087/101619302-0de67800-3a4e-11eb-9ec1-7d6efdc2b6ed.png)

**Comment by YummyLau** [comment]
@chenyp1994 是否是全屏场景。

**Comment by YummyLau** [comment]
@chenyp1994 更新到v1.3.13试试。

**Comment by chenyp1994** [comment]
我试试看。
