### ISSUE TITLE
感觉弄个复杂的布局，就好多问题。。。

### ISSUE THREAD

**Issue by najiutan** [YummyLau/PanelSwitchHelper#12]

**Comment by YummyLau** [comment]
如果感兴趣，你clone一份修改你的场景，我愿意clone你的场景看一下。
何方布局有多么复杂呢？
不介意的话可以贴你的场景代码。并描述逻辑，如果我能解决，可以给你建议。

**Comment by najiutan** [comment]
> 如果感兴趣，你clone一份修改你的场景，我愿意clone你的场景看一下。
> 何方布局有多么复杂呢？
> 不介意的话可以贴你的场景代码。并描述逻辑，如果我能解决，可以给你建议。
要不加个qq, 这里这样沟通太慢了，qq: 641930692

**Comment by YummyLau** [comment]
> > 如果感兴趣，你clone一份修改你的场景，我愿意clone你的场景看一下。
> > 何方布局有多么复杂呢？
> > 不介意的话可以贴你的场景代码。并描述逻辑，如果我能解决，可以给你建议。
> > 要不加个qq, 这里这样沟通太慢了，qq: 641930692

暂时没有qq。加个微信吧。 pursuit_of_720

**Comment by najiutan** [comment]
> pursuit_of_720

加了，通过下哈

**Comment by YummyLau** [comment]
复杂问题-done

**Comment by najiutan** [comment]
> 复杂问题-done

多谢帮忙，可以了，是我的布局有问题，了解不够深入，作者真是个热心肠的大神
