### ISSUE TITLE
目前不支持半屏的聊天界面是吗，输入法和表情面板显示有问题

### ISSUE THREAD

**Issue by Mrgl1203** [YummyLau/PanelSwitchHelper#121]

**Comment by Mrgl1203** [comment]
显示输入法：
D/LogTracker: PanelSwitchLayout(238163368)#checkoutPanel => checkout success ! lastPanel's id : -1 , panel's id :0
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :-846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 2196 
    localLocation[y]                                   = 1056 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,1056) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = -846 
    ContentContainerH                                  = 1224 
    PanelContainerTop                                  = 378 
    PanelContainerH                                    = 846 
    changeBounds                                       = true 
    reverseResetState                                  = true 
    contentContainer Layout                            = (0,-846,1080,378) 
    panelContainer Layout                              = (0,378,1080,1224) 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 2196 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => try to set KeyBoardHeight : 846，isShow true
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 1350 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 846, realKeyboardH : 846, isShown : false 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 1350 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 846 
    currentKeyboardInfo                                = keyboardH : 846, realKeyboardH : 846, isShown : true 
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :-846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 1350 
    localLocation[y]                                   = 228 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,228) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = -846 
    ContentContainerH                                  = 2052 
    PanelContainerTop                                  = 1206 
    PanelContainerH                                    = 846 
    changeBounds                                       = true 
    reverseResetState                                  = true 
    contentContainer Layout                            = (0,-846,1080,1206) 
    panelContainer Layout                              = (0,1206,1080,2052) 
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :-846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 1350 
    localLocation[y]                                   = 228 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,228) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = -846 
    ContentContainerH                                  = 2052 
    PanelContainerTop                                  = 1206 
    PanelContainerH                                    = 846 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-846,1080,1206) 
    panelContainer Layout                              = (0,1206,1080,2052) 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 1350 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 846 
    currentKeyboardInfo                                = keyboardH : 846, realKeyboardH : 846, isShown : true 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 1350 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 846 
    currentKeyboardInfo                                = keyboardH : 846, realKeyboardH : 846, isShown : true 
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :-846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 1350 
    localLocation[y]                                   = 228 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,228) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = -846 
    ContentContainerH                                  = 2052 
    PanelContainerTop                                  = 1206 
    PanelContainerH                                    = 846 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-846,1080,1206) 
    panelContainer Layout                              = (0,1206,1080,2052) 
2020-12-21 11:17:45.241 11701-11701/com.memezhibo.android D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 1350 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 846 
    currentKeyboardInfo                                = keyboardH : 846, realKeyboardH : 846, isShown : true 
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :-846
 D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 1350 
    localLocation[y]                                   = 228 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,228) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = -846 
    ContentContainerH                                  = 2052 
    PanelContainerTop                                  = 1206 
    PanelContainerH                                    = 846 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-846,1080,1206) 
    panelContainer Layout                              = (0,1206,1080,2052) 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 1350 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 846 
    currentKeyboardInfo                                = keyboardH : 846, realKeyboardH : 846, isShown : true 
隐藏输入法：
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :-846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 2196 
    localLocation[y]                                   = 1056 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,1056) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = -846 
    ContentContainerH                                  = 1224 
    PanelContainerTop                                  = 378 
    PanelContainerH                                    = 846 
    changeBounds                                       = true 
    reverseResetState                                  = true 
    contentContainer Layout                            = (0,-846,1080,378) 
    panelContainer Layout                              = (0,378,1080,1224) 
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :-846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 2196 
    localLocation[y]                                   = 1056 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,1056) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = -846 
    ContentContainerH                                  = 1224 
    PanelContainerTop                                  = 378 
    PanelContainerH                                    = 846 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-846,1080,378) 
    panelContainer Layout                              = (0,378,1080,1224) 
2020-12-21 11:18:26.710 11701-11701/com.memezhibo.android D/LogTracker: PanelSwitchLayout(238163368)#checkoutPanel => checkout success ! lastPanel's id : 0 , panel's id :-1
2020-12-21 11:18:26.711 11701-11701/com.memezhibo.android D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 2196 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 846 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : true 
2020-12-21 11:18:26.731 11701-11701/com.memezhibo.android D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 2196 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 2196 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :0
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 收起所有输入源 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 2196 
    localLocation[y]                                   = 1056 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,1056) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = 0 
    ContentContainerH                                  = 1224 
    PanelContainerTop                                  = 1224 
    PanelContainerH                                    = 846 
    changeBounds                                       = true 
    reverseResetState                                  = true 
    contentContainer Layout                            = (0,0,1080,1224) 
    panelContainer Layout                              = (0,1224,1080,2070) 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 2196 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 2196 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getCompatPanelHeight  :846
D/LogTracker: PanelSwitchLayout(238163368)#onLayout =>  getContentContainerTop  :0
D/LogTracker: PanelSwitchLayout(238163368)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 1224) 
    currentPanelState                                  = 收起所有输入源 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2280 
    screenH (static,exclude SystemUI)                  = 2201 
    screenH (dynamic,exclude SystemUI)                 = 2196 
    localLocation[y]                                   = 1056 
    toolbarH                                           = 0 
    StatusBarH                                         = 84 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,1056) 
    paddingTop                                         = 0 
    keyboardH                                          = 846 
    ContentContainerTop                                = 0 
    ContentContainerH                                  = 1224 
    PanelContainerTop                                  = 1224 
    PanelContainerH                                    = 846 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,0,1080,1224) 
    panelContainer Layout                              = (0,1224,1080,2070) 
D/LogTracker: PanelSwitchLayout(238163368)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2280 
    contentHeight                                      = 2196 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 84 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(0) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(0) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 84, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 84 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false

**Comment by YummyLau** [comment]
容器要全屏&透明，其他自由设计就好了。
