### ISSUE TITLE
低于4.4的报错

### ISSUE THREAD

**Issue by zhangzhen123** [YummyLau/PanelSwitchHelper#124]
Androidx版本：是
PanelSwitchHelper版本：v1.3.6
手机型号: 
手机系统版本： Android 4.2 4.3
问题描述：
Androidx版本的在低于4.4版本的手机系统会报错 我在想是否这android.transition.ChangeBounds
android.transition.TransitionManager两个类也换成androidx版的能否解决这个问题。
Log提供：
`java.lang.NoClassDefFoundError

android.transition.ChangeBounds`

1 com.effective.android.panel.view.PanelSwitchLayout.setTransition(PanelSwitchLayout.kt:559)
--
2 com.effective.android.panel.view.PanelSwitchLayout.onLayout(PanelSwitchLayout.kt:500)
3 android.view.View.layout(View.java:14172)
4 android.view.ViewGroup.layout(ViewGroup.java:4475)
5 androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1762)
6 android.view.View.layout(View.java:14172)
7 android.view.ViewGroup.layout(ViewGroup.java:4475)
8 android.widget.FrameLayout.onLayout(FrameLayout.java:507)
9 android.view.View.layout(View.java:14172)
10 android.view.ViewGroup.layout(ViewGroup.java:4475)
11 android.widget.LinearLayout.setChildFrame(LinearLayout.java:1869)
12 android.widget.LinearLayout.layoutVertical(LinearLayout.java:1727)
13 android.widget.LinearLayout.onLayout(LinearLayout.java:1640)

**Comment by zhangzhen123** [comment]
刚在demo改了下 可以运行 不过要导入implementation "androidx.transition:transition:1.2.0"依赖

**Comment by YummyLau** [comment]
@zhangzhen123  ChangeBounds 已经做了版本判断，按道理来说不应该会尝试链接 ChangeBounds。

**Comment by zhangzhen123** [comment]
> @ zhangzhen123 ChangeBounds已经完成版本确定，按道理来说不应该会尝试链接ChangeBounds。
> 启动就崩溃么？debug下能否进入setTransition外层条件。

都是线上报的 我这边也没有4.4一下的测试机😓

**Comment by YummyLau** [comment]
@zhangzhen123 4.4 我找个机子测试下。

**Comment by YummyLau** [comment]
目前测试了多个4.3手机并没有问题，可提供更具体的机型问题或者确认下主dex加载问题。
