### ISSUE TITLE
当聊天消息只有一两条消息时，面板弹起来就被顶上去就看不见了

### ISSUE THREAD

**Issue by wangzhanxian** [YummyLau/PanelSwitchHelper#125]

**Comment by YummyLau** [comment]
@wangzhanxian 有个api可以用，参考提供的api https://github.com/YummyLau/PanelSwitchHelper/blob/master/README_API-zh.md

addContentScrollMeasurer 方法

**Comment by wangzhanxian** [comment]
> @wangzhanxian 有个api可以用，参考提供的api https://github.com/YummyLau/PanelSwitchHelper/blob/master/README_API-zh.md
> 
> addContentScrollMeasurer 方法

谢谢，看到了
