### ISSUE TITLE
在DialogFragment中软键盘现实的时候其他面板还在？

### ISSUE THREAD

**Issue by wangfeigit** [YummyLau/PanelSwitchHelper#126]
这个是什么原因导致的，有解决办法吗

**Comment by YummyLau** [comment]
目前没有遇到过，提供下样本。 @wangfeigit

**Comment by wangfeigit** [comment]
问个问题，当dialog页面上的按钮点击跳转到其他页面，返回来的时候键盘消失了，系统软件盘换不起来了，这个怎么解决呢

**Comment by YummyLau** [comment]
你发给我的Demo处理了，严格参考 项目提供的Demo写没有问题的 。
