### ISSUE TITLE
收起软键盘后，列表无法滑动

### ISSUE THREAD

**Issue by caihuanjian** [YummyLau/PanelSwitchHelper#13]
收起软键盘，第一次滑动列表，列表无法滑动，事件被某个empty_view吃掉了？松开手指，再进行滑动才能触发聊天列表滑动

**Comment by YummyLau** [comment]
> 收起软键盘，第一次滑动列表，列表无法滑动，事件被某个empty_view吃掉了？松开手指，再进行滑动才能触发聊天列表滑动

什么版本，1.0.3吗

**Comment by caihuanjian** [comment]
> > 收起软键盘，第一次滑动列表，列表无法滑动，事件被某个empty_view吃掉了？松开手指，再进行滑动才能触发聊天列表滑动
> 
> 什么版本，1.0.3吗

是的

**Comment by YummyLau** [comment]
> > > 收起软键盘，第一次滑动列表，列表无法滑动，事件被某个empty_view吃掉了？松开手指，再进行滑动才能触发聊天列表滑动
> > 
> > 
> > 什么版本，1.0.3吗
> 
> 是的

刚才测试了下，我这里是正常的。
你贴一下你的layout，如果不方便的话，检测下你的emptyView是不是使用库提供的EmptyView。如果不是换成1.0.3提供的EmptyView。

**Comment by caihuanjian** [comment]
换成emptyview后可以了
