### ISSUE TITLE
用DialogFragment弹窗,复用它，不让每次打开都创建，会导致面板不出现，有什么解决方案

### ISSUE THREAD

**Issue by LebronXia** [YummyLau/PanelSwitchHelper#132]

**Comment by YummyLau** [comment]
可以复用的，可以提供下你的demo链接。

**Comment by LebronXia** [comment]
用你的Demo里的试也会有这样的问题
   case window_1:{
                        if (dialogFragment == null){
                            dialogFragment = new ChatDialogFragment();
                        }

                        dialogFragment.showNow(getSupportFragmentManager(), "dialogFragment");
                        break;
                    }

**Comment by LebronXia** [comment]
用你的Demo里的试也会有这样的问题
`   case window_1:{
                        if (dialogFragment == null){
                            dialogFragment = new ChatDialogFragment();
                        }

                        dialogFragment.showNow(getSupportFragmentManager(), "dialogFragment");
                        break;
                    }`

**Comment by YummyLau** [comment]
@LebronXia 因为demo没有兼容复用。dialogFragment在隐藏之后会回调 onDestroyView 。由于视图detachWindow会进而导致框架内部 PanelSwitchLayout触发recycler。所以在 showNow之前要对helper重新初始化，在onDestoryView 把 Helper设置为null就可以了。

**Comment by LebronXia** [comment]
2021-05-08 12:12:15.940 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2310 
    contentHeight                                      = 1246 
    isFullScreen                                       = false 
    isNavigationBarShown                               = true 
    deviceStatusBarH                                   = 103 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(103) top(0) right(0) bottom(961) 
    inset                                              = left(0) top(103) right(0) bottom(126) 
    currentSystemInfo                                  = statusBarH : 103, navigationBarH : 126 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 229 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 835, realKeyboardH : 835, isShown : false 
2021-05-08 12:12:16.025 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onLayout =>  getCompatPanelHeight  :835
2021-05-08 12:12:16.025 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onLayout =>  getContentContainerTop  :-835
2021-05-08 12:12:16.026 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 2079) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = true 
    screenH (static,include SystemUI)                  = 2310 
    screenH (static,exclude SystemUI)                  = 2081 
    screenH (dynamic,exclude SystemUI)                 = 1246 
    localLocation[y]                                   = -295 
    toolbarH                                           = 0 
    StatusBarH                                         = 103 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,-295) 
    paddingTop                                         = 0 
    keyboardH                                          = 835 
    ContentContainerTop                                = -835 
    ContentContainerH                                  = 2479 
    PanelContainerTop                                  = 1644 
    PanelContainerH                                    = 835 
    changeBounds                                       = true 
    reverseResetState                                  = true 
    contentContainer Layout                            = (0,-835,1080,1644) 
    panelContainer Layout                              = (0,1644,1080,2479)

**Comment by LebronXia** [comment]
2021-05-08 12:12:16.030 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onLayout =>  getCompatPanelHeight  :835
2021-05-08 12:12:16.030 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onLayout =>  getContentContainerTop  :-835
2021-05-08 12:12:16.031 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 1080 , b : 2079) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = true 
    screenH (static,include SystemUI)                  = 2310 
    screenH (static,exclude SystemUI)                  = 2081 
    screenH (dynamic,exclude SystemUI)                 = 1246 
    localLocation[y]                                   = -295 
    toolbarH                                           = 0 
    StatusBarH                                         = 103 
    NavigationBarH                                     = 126 
    layout Location                                    = (0,-295) 
    paddingTop                                         = 0 
    keyboardH                                          = 835 
    ContentContainerTop                                = -835 
    ContentContainerH                                  = 2479 
    PanelContainerTop                                  = 1644 
    PanelContainerH                                    = 835 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-835,1080,1644) 
    panelContainer Layout                              = (0,1644,1080,2479) 
2021-05-08 12:12:16.114 3505-3505/com.qiyu.world D/LogTracker: PanelSwitchLayout(160904078)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2310 
    contentHeight                                      = 1246 
    isFullScreen                                       = false 
    isNavigationBarShown                               = true 
    deviceStatusBarH                                   = 103 
    deviceNavigationBarH                               = 126 
    systemInset                                        = left(103) top(0) right(0) bottom(961) 
    inset                                              = left(0) top(103) right(0) bottom(126) 
    currentSystemInfo                                  = statusBarH : 103, navigationBarH : 126 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 229 
    minLimitCloseKeyboardH                             = 126 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 835 
    currentKeyboardInfo                                = keyboardH : 835, realKeyboardH : 835, isShown : true

**Comment by YummyLau** [comment]
你使用什么方案实现的，另外你弹出来的布局需要填充满父布局，可以参考demo

**Comment by LebronXia** [comment]
设置全屏解决了~
