### ISSUE TITLE
适配bug

### ISSUE THREAD

**Issue by weishl110** [YummyLau/PanelSwitchHelper#136]
PanelSwitchHelper：androidx-1.3.13
手机型号: LG K20
手机系统版本:android 9.0
问题：配合androidAutosize使用时，获取的statusbarheight小，DeviceRuntime中的getDeviceInfoByOrientation获取到的
navigationBarHeight、statusBarHeight、screenWithoutSystemUIHeight总和小于screenHeight

**Comment by YummyLau** [comment]
@weishl110 建议参考 https://github.com/JessYanCoding/AndroidAutoSize/issues/13。

**Comment by YummyLau** [comment]
AutoSize的issue反馈了很多第三方库显示异常的问题，理论上第三方不会做针对autoSize的适配，应该按照autoSize给的处理方法处理。

**Comment by weishl110** [comment]
好的，谢谢

**Comment by weishl110** [comment]
请教一个问题   DeviceRuntime 中的getDeviceInfoByOrientation 返回的DeviceInfo  为什么需要每次都重新获取呢？有成员变量记录，如果不为空，直接返回会有其它问题吗？我这边这样做可以解决我这边的问题。如果这样做不知道您们是否有遇到其它的问题。
