### ISSUE TITLE
从软键盘切换为面板的过程中有软键盘退出和面板进入的动画

### ISSUE THREAD

**Issue by sunzengyan1** [YummyLau/PanelSwitchHelper#137]
Androidx版本：是
PanelSwitchHelper版本：v1.3.13
手机型号: 红米K40
手机系统版本： Android 11
问题描述：类似acitivty自定义标题栏的页面，从软键盘切换为面板的过程中有软键盘退出和面板进入的动画。xml和class的代码都是从项目中拷贝的。实在找不到原因了，请帮帮忙，万分感谢。
Log日志：从软键盘切换为面板过程的log。
`2021-06-10 19:54:51.606 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout =>  getCompatPanelHeight  :988
2021-06-10 19:54:51.606 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout =>  getContentContainerTop  :-988
2021-06-10 19:54:51.606 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout#onLayout => ContentScrollMeasurer(id 2131296881 , defaultScrollHeight 988 , scrollDistance 988 reset false) origin (l 0,t 0,r 0, b 2044)
2021-06-10 19:54:51.606 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout#onLayout => ContentScrollMeasurer(id 2131296881 , defaultScrollHeight 988 , scrollDistance 988 reset false) layout parent(l 0,t -988,r 1080,b 1200) self(l 0,t 0,r 1080, b2044)
2021-06-10 19:54:51.606 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : true , l : 0  , t : 132 , r : 1080 , b : 2320) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2400 
    screenH (static,exclude SystemUI)                  = 2276 
    screenH (dynamic,exclude SystemUI)                 = 2320 
    localLocation[y]                                   = 212 
    toolbarH                                           = 0 
    StatusBarH                                         = 80 
    NavigationBarH                                     = 48 
    layout Location                                    = (0,212) 
    paddingTop                                         = 0 
    keyboardH                                          = 988 
    ContentContainerTop                                = -988 
    ContentContainerH                                  = 2188 
    PanelContainerTop                                  = 1200 
    PanelContainerH                                    = 988 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-988,1080,1200) 
    panelContainer Layout                              = (0,1200,1080,2188) 
2021-06-10 19:54:51.609 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#checkoutPanel => checkout success ! lastPanel's id : 0 , panel's id :-1
2021-06-10 19:54:51.609 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2400 
    contentHeight                                      = 2320 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 80 
    deviceNavigationBarH                               = 48 
    systemInset                                        = left(80) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(80) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 80, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 80 
    minLimitCloseKeyboardH                             = 48 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 988 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : true 
2021-06-10 19:54:51.613 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout =>  getCompatPanelHeight  :988
2021-06-10 19:54:51.613 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout =>  getContentContainerTop  :0
2021-06-10 19:54:51.613 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout#onLayout => ContentScrollMeasurer(id 2131296881 , defaultScrollHeight 988 , scrollDistance 0 reset true) origin (l 0,t 0,r 0, b 2044)
2021-06-10 19:54:51.613 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout#onLayout => ContentScrollMeasurer(id 2131296881 , defaultScrollHeight 988 , scrollDistance 0 reset true) layout parent(l 0,t 0,r 1080,b 2188) self(l 0,t 0,r 1080, b2044)
2021-06-10 19:54:51.613 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 132 , r : 1080 , b : 2320) 
    currentPanelState                                  = 收起所有输入源 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2400 
    screenH (static,exclude SystemUI)                  = 2276 
    screenH (dynamic,exclude SystemUI)                 = 2320 
    localLocation[y]                                   = 212 
    toolbarH                                           = 0 
    StatusBarH                                         = 80 
    NavigationBarH                                     = 48 
    layout Location                                    = (0,212) 
    paddingTop                                         = 0 
    keyboardH                                          = 988 
    ContentContainerTop                                = 0 
    ContentContainerH                                  = 2188 
    PanelContainerTop                                  = 2188 
    PanelContainerH                                    = 988 
    changeBounds                                       = true 
    reverseResetState                                  = true 
    contentContainer Layout                            = (0,0,1080,2188) 
    panelContainer Layout                              = (0,2188,1080,3176) 
2021-06-10 19:54:51.615 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2400 
    contentHeight                                      = 2320 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 80 
    deviceNavigationBarH                               = 48 
    systemInset                                        = left(80) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(80) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 80, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 80 
    minLimitCloseKeyboardH                             = 48 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
2021-06-10 19:54:51.658 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout =>  getCompatPanelHeight  :988
2021-06-10 19:54:51.659 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#checkoutPanel => checkout success ! lastPanel's id : -1 , panel's id :2131296614
2021-06-10 19:54:51.664 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2400 
    contentHeight                                      = 2320 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 80 
    deviceNavigationBarH                               = 48 
    systemInset                                        = left(80) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(80) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 80, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 80 
    minLimitCloseKeyboardH                             = 48 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
2021-06-10 19:54:51.829 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout =>  getCompatPanelHeight  :988
2021-06-10 19:54:51.829 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout =>  getContentContainerTop  :-988
2021-06-10 19:54:51.830 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout#onLayout => ContentScrollMeasurer(id 2131296881 , defaultScrollHeight 988 , scrollDistance 988 reset false) origin (l 0,t 0,r 0, b 2044)
2021-06-10 19:54:51.830 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout#onLayout => ContentScrollMeasurer(id 2131296881 , defaultScrollHeight 988 , scrollDistance 988 reset false) layout parent(l 0,t -988,r 1080,b 1200) self(l 0,t 0,r 1080, b2044)
2021-06-10 19:54:51.830 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onLayout => 界面每一次 layout 的信息回调 
    layoutInfo                                         = onLayout(changed : false , l : 0  , t : 132 , r : 1080 , b : 2320) 
    currentPanelState                                  = 显示面板输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = false 
    screenH (static,include SystemUI)                  = 2400 
    screenH (static,exclude SystemUI)                  = 2276 
    screenH (dynamic,exclude SystemUI)                 = 2320 
    localLocation[y]                                   = 212 
    toolbarH                                           = 0 
    StatusBarH                                         = 80 
    NavigationBarH                                     = 48 
    layout Location                                    = (0,212) 
    paddingTop                                         = 0 
    keyboardH                                          = 988 
    ContentContainerTop                                = -988 
    ContentContainerH                                  = 2188 
    PanelContainerTop                                  = 1200 
    PanelContainerH                                    = 988 
    changeBounds                                       = true 
    reverseResetState                                  = true 
    contentContainer Layout                            = (0,-988,1080,1200) 
    panelContainer Layout                              = (0,1200,1080,2188) 
2021-06-10 19:54:51.830 22459-22459/com.duanfeng.assemblechat D/LogTracker: PanelSwitchLayout(125894269)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 2400 
    contentHeight                                      = 2320 
    isFullScreen                                       = false 
    isNavigationBarShown                               = false 
    deviceStatusBarH                                   = 80 
    deviceNavigationBarH                               = 48 
    systemInset                                        = left(80) top(0) right(0) bottom(0) 
    inset                                              = left(0) top(80) right(0) bottom(0) 
    currentSystemInfo                                  = statusBarH : 80, navigationBarH : 0 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 80 
    minLimitCloseKeyboardH                             = 48 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 0 
    currentKeyboardInfo                                = keyboardH : 0, realKeyboardH : 0, isShown : false 
`

下面是xml代码：
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:id="@+id/ll_conversation"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="@dimen/title_bar_height"
        android:background="@color/colorPrimary">

        <include layout="@layout/layout_back" />

        <TextView
            android:id="@+id/tv_title"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_centerInParent="true"
            android:textColor="@color/black_333"
            android:textSize="18sp"
            android:textStyle="bold" />

        <ImageButton
            android:id="@+id/ib_more"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_alignParentRight="true"
            android:layout_centerVertical="true"
            android:layout_marginRight="10dp"
            android:background="@mipmap/sangedian" />
    </RelativeLayout>

    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:animationSpeed="standard">

        
        
        
        <com.effective.android.panel.view.content.RelativeContentContainer
            android:id="@+id/content_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            app:auto_reset_enable="false"
            app:edit_view="@id/et_input"
            tools:layout_height="400dp">

            <com.duanfeng.assemblechat.ui.view.AutoHidePanelRecyclerView
                android:id="@+id/rv_conversation"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_above="@+id/bottom_action"
                android:tag="recycler_view" />

            <LinearLayout
                android:id="@+id/bottom_action"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:background="@color/gray_efefef"
                android:minHeight="48dp"
                android:paddingLeft="10dp"
                android:paddingRight="10dp">

                <ImageButton
                    android:id="@+id/ib_voiceortext"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginBottom="12dp"
                    android:layout_gravity="bottom"
                    android:background="@drawable/select_voice" />

                <EditText
                    android:id="@+id/et_input"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:layout_marginRight="10dp"
                    android:layout_marginTop="10dp"
                    android:layout_weight="1"
                    android:textSize="14sp"
                    android:maxLines="5"
                    android:padding="5dp"
                    android:background="@drawable/shape_et_bg_msg_input" />

                <TextView
                    android:id="@+id/tv_press_talk"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_marginLeft="10dp"
                    android:layout_marginRight="10dp"
                    android:layout_marginTop="8dp"
                    android:layout_marginBottom="8dp"
                    android:layout_weight="1"
                    android:padding="5dp"
                    android:background="@drawable/shape_et_bg_msg_input"
                    android:gravity="center"
                    android:text="按住说话"
                    android:textColor="@color/black_333"
                    android:textSize="14sp"
                    android:visibility="gone" />

                <ImageButton
                    android:id="@+id/ib_faceortext"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_marginRight="10dp"
                    android:layout_marginBottom="12dp"
                    android:layout_gravity="bottom"
                    android:background="@drawable/select_emoj" />

                <ImageButton
                    android:id="@+id/ib_add"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:visibility="visible"
                    android:layout_gravity="bottom"
                    android:layout_marginBottom="12dp"
                    android:background="@mipmap/add" />

                <TextView
                    android:id="@+id/tv_send"
                    android:layout_width="50dp"
                    android:layout_height="30dp"
                    android:background="@drawable/shape_bg_button_red"
                    android:text="发送"
                    android:gravity="center"
                    android:layout_gravity="bottom"
                    android:textColor="@color/white"
                    android:textSize="12sp"
                    android:layout_marginBottom="4dp"
                    android:visibility="gone" />
            </LinearLayout>

        </com.effective.android.panel.view.content.RelativeContentContainer>

        <com.effective.android.panel.view.panel.PanelContainer
            android:id="@+id/panel_container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:background="@color/colorPrimary"
            tools:layout_height="0dp"
            tools:layout_weight="1">

            
            
            
            
            <com.effective.android.panel.view.panel.PanelView
                android:id="@+id/panel_emotion"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:panel_layout="@layout/panel_emotion_layout"
                app:panel_trigger="@id/ib_faceortext" />

            <com.effective.android.panel.view.panel.PanelView
                android:id="@+id/panel_addition"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                app:panel_layout="@layout/panel_add_layout"
                app:panel_trigger="@id/ib_add" />

        </com.effective.android.panel.view.panel.PanelContainer>

    </com.effective.android.panel.view.PanelSwitchLayout>

</LinearLayout>`

**Comment by YummyLau** [comment]
@sunzengyan1 传个gif/视频看一下。

**Comment by sunzengyan1** [comment]
https://user-images.githubusercontent.com/25221254/121626253-add99880-caa7-11eb-9ab3-34daadb3d5dc.mp4

@YummyLau 这个是视频

**Comment by sunzengyan1** [comment]
> @sunzengyan1 传个gif/视频看一下。

您好，我找到原因了，我BaseActivity中写了点击空白地方隐藏软键盘的代码。注销代码后就没这个问题了，麻烦您了。下面是我BaseActivity中的代码。给大家做个记录，防止其他朋友遇到这种问题无处着手。
`@Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (ev.getAction() == MotionEvent.ACTION_DOWN) {
            View v = getCurrentFocus();
            if (isShouldHideKeyboard(v, ev)) {
                KeyboardUtils.hideSoftInput(this);
            }
        }
        return super.dispatchTouchEvent(ev);
    }

    // Return whether touch the view.
    private boolean isShouldHideKeyboard(View v, MotionEvent event) {
        if ((v instanceof EditText)) {
            int[] l = {0, 0};
            v.getLocationOnScreen(l);
            int left = l[0],
                    top = l[1],
                    bottom = top + v.getHeight(),
                    right = left + v.getWidth();
            return !(event.getRawX() > left && event.getRawX() < right
                    && event.getRawY() > top && event.getRawY() < bottom);
        }
        return false;
    }`
