### ISSUE TITLE
三星GalaxyS9存在页面跳动，遮挡问题

### ISSUE THREAD

**Issue by lovely3x** [YummyLau/PanelSwitchHelper#140]
问题详情视频
https://user-images.githubusercontent.com/7817253/122514741-04624c00-d03f-11eb-847f-77af2af04b34.mp4

机型：三星GalaxyS9
机型详细信息截图
![123](https://user-images.githubusercontent.com/7817253/122514976-55724000-d03f-11eb-992b-5f05c9cea0dd.png)

**Comment by YummyLau** [comment]
我找个测试机测试下。

**Comment by YummyLau** [comment]
新版 v1.4.0 已兼容，更新试一下。
