### ISSUE TITLE
华为横屏情况下，弹出的是悬浮键盘，该如何处理呢？

### ISSUE THREAD

**Issue by littlezan** [YummyLau/PanelSwitchHelper#142]
弹出的键盘不是正常的键盘，目前只出现在华为手机上，其他手机没有问题，很奇怪
![image](https://user-images.githubusercontent.com/5358278/126115609-db865a88-d9fa-46a8-88b6-b9eac7a264e4.png)

**Comment by YummyLau** [comment]
这个看起来是系统设置的。框架不会拉起悬浮软键盘，你看下手机设置。
