### ISSUE TITLE
设置autosize后，点开键盘再收起底部会有部分面板的内容收不了

### ISSUE THREAD

**Issue by Wucha1002** [YummyLau/PanelSwitchHelper#148]
- Androidx版本：是
- PanelSwitchHelper版本：v1.3.13
- 手机型号: 红米k40 pro
- 手机系统版本： Android 11

![IMG_20210804_150718](https://user-images.githubusercontent.com/40201862/128140273-e3fd472a-a277-461a-a54f-64976198a0a7.jpg)

取消autosize适配收起面板正常：
![IMG_20210804_150841](https://user-images.githubusercontent.com/40201862/128140034-b1b3c68e-d946-447e-940d-d38e81f5c58b.jpg)

**Comment by YummyLau** [comment]
@Wucha1002 autoSize更改了系统api的高度，太难了。如果用了autoSize需要 fork代码自己调整了。
