### ISSUE TITLE
切换的时候一卡一卡的.....

### ISSUE THREAD

**Issue by tokiii** [YummyLau/PanelSwitchHelper#15]

**Comment by tokiii** [comment]
表情切换键盘和键盘切换表情都是这样，华为荣耀10

**Comment by YummyLau** [comment]
> 表情切换键盘和键盘切换表情都是这样，华为荣耀10

Demo 卡顿还是业务页面卡顿的。

**Comment by tokiii** [comment]
Demo卡顿，方便的话可以发视频给你，用QQ

**Comment by YummyLau** [comment]
> Demo卡顿，方便的话可以发视频给你，用QQ

好的，感谢。不过我没有qq，方便的话添加下微信。 我的微信 pursuit_of_720

**Comment by tokiii** [comment]
加你了

**Comment by YummyLau** [comment]
华为导航栏动态隐藏的问题。问题已经定位了，适配性的工作正在进行，这种rom上的定制确实比较难搞。

**Comment by YummyLau** [comment]
已经修复。 1.0.5版本
