### ISSUE TITLE
在bottomsheetDialogFragment中，使用smartrefresh+recyclerview,设置builder 后出现滑动冲突，不设置则滑动正常

### ISSUE THREAD

**Issue by QianHong** [YummyLau/PanelSwitchHelper#150]
在bottomsheetDialogFragment中，使用smartrefresh+recyclerview,设置builder 后出现滑动冲突，不设置则滑动正常，但是出现输入法框和键盘出现小部分重叠。

`<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <data>

    </data>

    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/read_bg_comment_top"
        app:animationSpeed="standard">

        <com.effective.android.panel.view.content.RelativeContentContainer
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:edit_view="@id/edit_text">

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:layout_marginBottom="@dimen/spacing_50"
                android:orientation="vertical">

                <androidx.constraintlayout.widget.ConstraintLayout
                    android:id="@+id/cl_header"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content">

                    <ImageView
                        android:id="@+id/iv_close"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:layout_marginStart="@dimen/spacing_14"
                        android:paddingTop="@dimen/spacing_14"
                        android:paddingBottom="@dimen/spacing_14"
                        android:src="@drawable/read_paragraph_ic_close_down"
                        app:layout_constraintBottom_toTopOf="@id/split_line"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="parent"
                        app:layout_constraintVertical_chainStyle="spread_inside" />

                    <TextView
                        android:id="@+id/tv_title"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:text="@string/read_strings_paragraph_comment"
                        android:textColor="@color/color_text_1c1c1c"
                        android:textSize="@dimen/font_20"
                        android:textStyle="bold"
                        app:layout_constraintBottom_toBottomOf="@id/iv_close"
                        app:layout_constraintEnd_toEndOf="parent"
                        app:layout_constraintStart_toStartOf="parent"
                        app:layout_constraintTop_toTopOf="@id/iv_close" />

                    <View
                        android:id="@+id/split_line"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/spacing_1"
                        android:background="@color/color_f4f4f4"
                        app:layout_constraintBottom_toBottomOf="parent"
                        app:layout_constraintTop_toBottomOf="@id/iv_close" />

                </androidx.constraintlayout.widget.ConstraintLayout>

                <com.scwang.smartrefresh.layout.SmartRefreshLayout
                    android:id="@+id/refresh_layout"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:srlEnableNestedScrolling="false"
                    app:srlEnableRefresh="false">

                    <com.dpx.kjemoji.emotion.widget.AutoHidePanelRecyclerView
                        android:id="@+id/recycler_view"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:background="@color/white" />

                </com.scwang.smartrefresh.layout.SmartRefreshLayout>
            </LinearLayout>

            <androidx.constraintlayout.widget.ConstraintLayout
                android:id="@+id/add_comment_layout"
                android:layout_width="match_parent"
                android:layout_height="@dimen/spacing_50"
                android:layout_alignParentBottom="true"
                android:background="@color/white">

                <TextView
                    android:id="@+id/add_comment_text_view"
                    android:layout_width="fill_parent"
                    android:layout_height="@dimen/spacing_30"
                    android:layout_gravity="center_vertical"
                    android:layout_marginLeft="@dimen/spacing_16"
                    android:layout_marginRight="@dimen/spacing_56"
                    android:background="@drawable/shape_round_rect_solid_black_transparent"
                    android:ellipsize="end"
                    android:gravity="center_vertical"
                    android:maxLines="1"
                    android:paddingLeft="@dimen/spacing_16"
                    android:paddingRight="@dimen/spacing_16"
                    android:text="@string/story_comment_edit_hint"
                    android:textSize="12.0sp"
                    app:layout_constraintBottom_toBottomOf="parent"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintTop_toTopOf="parent" />

                <ImageView
                    android:id="@+id/image_view"
                    android:layout_width="@dimen/spacing_56"
                    android:layout_height="match_parent"
                    android:layout_gravity="bottom|center|right"
                    android:scaleType="center"
                    android:src="@mipmap/ic_comment_send"
                    app:layout_constraintEnd_toEndOf="parent" />
            </androidx.constraintlayout.widget.ConstraintLayout>

            <com.dpx.kjemoji.emotion.widget.EmotiocnsKeyBoardV2
                android:id="@+id/emoticons_keyboard"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:visibility="gone" />
        </com.effective.android.panel.view.content.RelativeContentContainer>

        <com.effective.android.panel.view.panel.PanelContainer
            android:layout_width="match_parent"
            android:layout_height="match_parent">

            <com.effective.android.panel.view.panel.PanelView
                android:id="@+id/panel_emotion"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:panel_layout="@layout/panel_grid_listemotion_layout"
                app:panel_trigger="@id/emotion_btn" />
        </com.effective.android.panel.view.panel.PanelContainer>
    </com.effective.android.panel.view.PanelSwitchLayout>
`

![image](https://user-images.githubusercontent.com/22974738/132148508-8af82b78-c9cd-4500-8659-94ce71e25809.png)

**Comment by YummyLau** [comment]
有更多反馈可重新打开issue讨论。
