### ISSUE TITLE
How to implement in fragment?

### ISSUE THREAD

**Issue by abkoradiya** [YummyLau/PanelSwitchHelper#152]
Hi, Thanks for the wonderful library.
I have one question. If I have small height fragment in activity and need to implement panel in that fragment, How can I implement like this? I have tried but it is not working.

**Comment by abkoradiya** [comment]
This is the log

layoutInfo                                         = onLayout(changed : false , l : 0  , t : 0 , r : 720 , b : 831) 
    currentPanelState                                  = 显示键盘输入 
    isPad                                              = false 
    isFullScreen                                       = false 
    isPortrait                                         = true 
    isNavigationShown                                  = true 
    screenH (static,include SystemUI)                  = 1520 
    screenH (static,exclude SystemUI)                  = 1391 
    screenH (dynamic,exclude SystemUI)                 = 831 
    localLocation[y]                                   = 54 
    toolbarH                                           = 0 
    StatusBarH                                         = 54 
    NavigationBarH                                     = 75 
    layout Location                                    = (0,54) 
    paddingTop                                         = 0 
    keyboardH                                          = 560 
    ContentContainerTop                                = -560 
    ContentContainerH                                  = 1391 
    PanelContainerTop                                  = 831 
    PanelContainerH                                    = 560 
    changeBounds                                       = false 
    contentContainer Layout                            = (0,-560,720,831) 
    panelContainer Layout                              = (0,831,720,1391) 
2021-09-15 11:16:49.247 18469-18469/com.example D/LogTracker: PanelSwitchLayout(14111628)#onGlobalLayout => 界面每一次变化的信息回调 
    windowSoftInputMode                                = 19 
    currentPanelSwitchLayoutVisible                    = true 
    screenHeight                                       = 1520 
    contentHeight                                      = 831 
    isFullScreen                                       = false 
    isNavigationBarShown                               = true 
    deviceStatusBarH                                   = 54 
    deviceNavigationBarH                               = 75 
    systemInset                                        = left(54) top(0) right(0) bottom(635) 
    inset                                              = left(0) top(54) right(0) bottom(75) 
    currentSystemInfo                                  = statusBarH : 54, navigationBarH : 75 全面屏手势虚拟栏H : 0 
    currentSystemH                                     = 129 
    minLimitCloseKeyboardH                             = 75 
    minLimitOpenKeyboardH                              = 300 
    lastKeyboardH                                      = 560 
    currentKeyboardInfo                                = keyboardH : 560, realKeyboardH : 560, isShown : true

**Comment by YummyLau** [comment]
Hello, if you are a fragment with a small layout, it doesn't matter, it's like the fragment is embedded in the activity's viewPager. You need to look at your specific scenario, and provide a more specific demo video or code if it is convenient.
