### ISSUE TITLE
自定义EditText不弹键盘

### ISSUE THREAD

**Issue by visir-he** [YummyLau/PanelSwitchHelper#154]
如题，如果是自定义输入框，就算什么都不做，什么方法都不重写，都不能弹出键盘来。不乱是点击输入框，还是调用[PanelSwitchHelper.toKeyboardState()]方法都不行。

**Comment by YummyLau** [comment]
@visir-he 传个demo或者项目链接

**Comment by visir-he** [comment]
> @visir-he 传个demo或者项目链接

你可以就在这个项目demo上面随便把一个输入控件改为自定义的控件试试，我这边在你的demo上改了一下也是不行的。

**Comment by YummyLau** [comment]
我这里处理是没有问题的。即使是自定义控件，至少也要edittext子类。可以看下框架原理。
