### ISSUE TITLE
CoordinatorLayout+ViewPager会出现问题

### ISSUE THREAD

**Issue by pengbig** [YummyLau/PanelSwitchHelper#157]
- [ ]
![651635933464_ pic_hd](https://user-images.githubusercontent.com/38551831/140040409-0925e025-1d04-4197-a013-1e4222ad8d33.jpg)
  
底部会有一个高度

**Comment by YummyLau** [comment]
看起来你的布局可能用错了。具体得看你怎么排版。方便可以提供下实现或者加讨论群说一下具体实现。
