### ISSUE TITLE
大家还希望 PanelSwitchHelper 新增哪些功能？欢迎大家盖楼。

### ISSUE THREAD

**Issue by YummyLau** [YummyLau/PanelSwitchHelper#16]
鉴于自己的兴趣爱好，本库会长期维护，提议的功能将会被审核开发。

**Comment by zicen** [comment]
如果要默认进来就显示软键盘，应该怎么做？我试着在 onResume 的时候调用了一下 PanelHelper.showKeyboard 但是没有效果。如果可以的话，是不是可以加个这个配置？

**Comment by zicen** [comment]
@Override
    public void onResume() {
        super.onResume();
        editText.post(new Runnable() {
            @Override
            public void run() {
                PanelHelper.showKeyboard(getContext(),editText);
            }
        });
    }

这样可以了。

**Comment by YummyLau** [comment]
> @override
> public void onResume() {
> super.onResume();
> editText.post(new Runnable() {
> @override
> public void run() {
> PanelHelper.showKeyboard(getContext(),editText);
> }
> });
> }
> 
> 这样可以了。

在构建 PanelSwitchHelper对象的时候可以使用 

```
mHelper = new PanelSwitchHelper.Builder(this)
.xxxx()
.build(true);
```
即可。

**Comment by lvsecoto** [comment]
Panel在展开和收起时可以带平滑切换效果

**Comment by YummyLau** [comment]
> Panel在展开和收起时可以带平滑切换效果

嗯已在考虑之内。如果有效果图，可以贴一下，或者推荐一下某些产品的效果。

**Comment by lvsecoto** [comment]
> > Panel在展开和收起时可以带平滑切换效果
> 
> 嗯已在考虑之内。如果有效果图，可以贴一下，或者推荐一下某些产品的效果。

微信现在就有啊，最新版的

**Comment by YummyLau** [comment]
@lvsecoto 
1.1.0已经更新支持动画了。可见readMe。

**Comment by YummyLau** [comment]
1.1.1 支持异型屏，如有特殊机型有问题可留言适配。

**Comment by 121493359** [comment]
希望增加底部panel部分可以指定高度功能，就是说panelview高度可变

**Comment by YummyLau** [comment]
> 希望增加底部panel部分可以指定高度功能，就是说panelview高度可变

panelView的高度是可变的，但是前提是输入法的高度产生了变化，panelView的高度就会有一个回调变化，这部分框架已经支持了，业务可以根据回调的高度自行更改自己的UI显示。不知道是否满足你说的panelView高度可变。

**Comment by 121493359** [comment]
目前panelView应该是和输入法高度一致的，不知道这点我理解是否对。如果是这样，那我上面指的是panelView可以提前指定固定高度(可能ui给个固定值)， panelView高度和输入法不一致的情况。我看微信的表情高度和输入法高度有可能不一样，比如的mi 9se，有虚拟导航栏的时候。

**Comment by YummyLau** [comment]
> 目前panelView应该是和输入法高度一致的，不知道这点我理解是否对。如果是这样，那我上面指的是panelView可以提前指定固定高度(可能ui给个固定值)， panelView高度和输入法不一致的情况。我看微信的表情高度和输入法高度有可能不一样，比如的mi 9se，有虚拟导航栏的时候。

实际上这个框架就要用来避免面板高度与输入法高度差异所带来的体验问题。  新版本虚拟系统ui也会被动态计算然后这部分高度会还给内容面板。  
1. 微信表情面板与输入法高度不一致的时候，我的测试机型中有多款体验并不好，一开始是允许的，但是在框架1.0就实现了要自动跟随输入法版本。gif有展示的。
2. 基于1问题，所以定的思路是，面板与输入法达到一致高度进而在多个面板中切换保证界面不会跳动，这很重要。因为要考虑多个面板可能存在高度差异，与输入法也存在差异。所以最终的做法是把高度开放给外部监听，让外部根据变动调整panel内部的UI。但是整体的高度是不变的，只能调整内部布局。就像demo一样，拉伸输入法，会让emoji动态调整，如果不要动态调整，就写一个最低的高度然后居中也是可以的。

**Comment by YummyLau** [comment]
> 目前panelView应该是和输入法高度一致的，不知道这点我理解是否对。如果是这样，那我上面指的是panelView可以提前指定固定高度(可能ui给个固定值)， panelView高度和输入法不一致的情况。我看微信的表情高度和输入法高度有可能不一样，比如的mi 9se，有虚拟导航栏的时候。

实际上这个框架就要用来避免面板高度与输入法高度差异所带来的体验问题。 新版本虚拟系统ui也会被动态计算然后这部分高度会还给内容面板。

   1. 微信表情面板与输入法高度不一致的时候，我的测试机型中有多款体验并不好，一开始是允许的，但是在框架1.0就实现了要自动跟随输入法高度。gif有展示的。
   2. 基于1问题，所以定的思路是，面板与输入法达到一致高度进而在多个面板中切换保证界面不会跳动，这很重要。因为要考虑多个面板可能存在高度差异，与输入法也存在差异。所以最终的做法是把高度开放给外部监听，让外部根据变动调整panel内部的UI。但是整体的高度是不变的，只能调整内部布局。就像demo一样，拉伸输入法，会让emoji动态调整，如果不要动态调整，就写一个最低的高度然后居中也是可以的。

**Comment by YummyLau** [comment]
> 目前panelView应该是和输入法高度一致的，不知道这点我理解是否对。如果是这样，那我上面指的是panelView可以提前指定固定高度(可能ui给个固定值)， panelView高度和输入法不一致的情况。我看微信的表情高度和输入法高度有可能不一样，比如的mi 9se，有虚拟导航栏的时候。

你的理解是对的。
实际上这个框架就要用来避免面板高度与输入法高度差异所带来的体验问题。 新版本虚拟系统ui也会被动态计算然后这部分高度会还给内容面板。

  1. 微信表情面板与输入法高度不一致的时候，我的测试机型中有多款体验并不好，一开始是允许的，但是在框架1.0就实现了要自动跟随输入法高度。gif有展示的。
  2. 基于1问题，所以定的思路是，面板与输入法达到一致高度进而在多个面板中切换保证界面不会跳动，这很重要。因为要考虑多个面板可能存在高度差异，与输入法也存在差异。所以最终的做法是把高度开放给外部监听，让外部根据变动调整panel内部的UI。但是整体的高度是不变的，只能调整内部布局。就像demo一样，拉伸输入法，会让emoji动态调整，如果不要动态调整，就写一个最低的高度然后居中也是可以的。

**Comment by 121493359** [comment]
好的，多谢回复

**Comment by androidwzl** [comment]
![image](https://user-images.githubusercontent.com/10822963/79039702-bc16f500-7c15-11ea-824c-1ea2b6623172.png)这种非全屏的底部dialog编辑框，似乎并不支持

**Comment by YummyLau** [comment]
> ![image](https://user-images.githubusercontent.com/10822963/79039702-bc16f500-7c15-11ea-824c-1ea2b6623172.png)这种非全屏的底部dialog编辑框，似乎并不支持
> ![BD9C3962-6F9F-4bb7-B950-482E8CB556C8](https://user-images.githubusercontent.com/10822963/79039764-12843380-7c16-11ea-8255-73be7a81b0a7.png)

根布局不支持动态高度的。根布局一般需要全屏才能有效计算各种高度。

**Comment by Firefly822** [comment]
@YummyLau  麻烦问个问题， 如果列表的条数很少，弹出键盘的时候，不需要将布局顶上去，这个怎么办？

**Comment by YummyLau** [comment]
@Firefly822 之前旧版本，window的窗口更改的时候，从设备顶部往下绘制，没有这个问题。新版为了动画更为流畅，发生resize的时候，让布局往上layout做动画，这个后续优化下。会存在这个问题

**Comment by YummyLau** [comment]
@Firefly822 目前已经有方案可以解决了，周末处理下。

**Comment by YummyLau** [comment]
@Firefly822  v1.1.2 done ,可参考更新的功能及demo

**Comment by YummyLau** [comment]
v1.3.0 支持 聊天场景/直播场景/视频播放场景/类朋友圈信息流评论场景。

**Comment by ender115** [comment]
emoji表情除了固定的，还可以动态添加自定义表情，可以是类似微信那种固定的emoji表情上下滑动，左右滑的话就在固定的emoji表情和自定义表情之间切换，或者是都是左右滑动，固定的emoji表情滑完以后就滑到自定义表情，也可以点击tab在固定表情和自定义表情间切换

**Comment by YummyLau** [comment]
@ender115 这个其实在自己的业务面板里面扩展就好啦。一般框架层不提供业务化的功能。

**Comment by huanghaoming** [comment]
可否支持打开面板时有灰色遮罩遮住内容呢。。如果已经实现，可否提供思考

**Comment by YummyLau** [comment]
@huanghaoming 不知道你的具体场景是怎样的。这个比较好实现，你盖一个view就可以实现了，框架不干预。如果盖住是为了拦截点击隐藏，框架已经自动处理了。

**Comment by huanghaoming** [comment]
> @huanghaoming 不知道你的具体场景是怎样的。这个比较好实现，你盖一个view就可以实现了，框架不干预。如果盖住是为了拦截点击隐藏，框架已经自动处理了。

谢谢答复，我看到你的demo里都是聊天窗口。。我的应用场景是评论回复。。。例如知乎里的写评论。

**Comment by YummyLau** [comment]
。。下面有很多场景，知乎那种，有很多中方法实现。你可以可用dialog，或者popupwindow。也可以写在和评论列表同一层。。

**Comment by huanghaoming** [comment]
> 。。下面有很多场景，知乎那种，有很多中方法实现。你可以可用dialog，或者popupwindow。也可以写在和评论列表同一层。。 @huanghaoming

谢谢。。我会尝试自己写一个view来试试。。。不过你demo里的dialog那种不知道能不能实现。。因为我想实现的是仅仅将面板通过dialog方式弹出，demo里的则是将所有内容都装进dialog里了对吗

**Comment by huanghaoming** [comment]
> > 。。下面有很多场景，知乎那种，有很多中方法实现。你可以可用dialog，或者popupwindow。也可以写在和评论列表同一层。。 @huanghaoming
> 
> 谢谢。。我会尝试自己写一个view来试试。。。不过你demo里的dialog那种不知道能不能实现。。因为我想实现的是仅仅将面板通过dialog方式弹出，demo里的则是将所有内容都装进dialog里了对吗

其实我的需求跟demo里的“微信朋友圈”很类似。。不过我还是想加个遮罩，让面板和内容从视觉上分开一点。（产品方面的问题了，哈哈）

**Comment by huanghaoming** [comment]
你好。。有没有兴趣支持一些BottomSheetDialogFragment呢。。。

**Comment by YummyLau** [comment]
@huanghaoming 其实它本质就是一个DialogFragment，DialogFragment已经支持了。

**Comment by Alexxiaopang** [comment]
真心建议工程也放一下码云吧，github的抽筋网络，有梯子都慢成狗，clone都很慢

**Comment by abcdisgreat** [comment]
git下载文件真的大，没梯子半个小时都没下好

**Comment by YummyLau** [comment]
@YummyLau @abcdisgreat 把gif压缩到极致了。可以试试。或者直接扫码下载demo

**Comment by st237688100** [comment]
目前的键盘弹出之后，布局变化的动画实现，导致列表有一部分内容在屏幕之外，使得列表滑动到最顶端也无法看到第一行视图，这种一般会被看成bug的。麻烦增加这个feature，或者提供下好的思路。

**Comment by YummyLau** [comment]
@st237688100 目前是动态切换模式来处理，先默认固定模式后根据内容填充来切换滑动模式。这个场景确实比较难搞。demo下个版本会优化并且readme更下 思路。

**Comment by YummyLau** [comment]
@st237688100 v1.3.3 已经兼容了 “导致列表有一部分内容在屏幕之外” 的问题。

**Comment by Alexxiaopang** [comment]
Tablayout+Fragment（虎牙效果），在很多手机，先弹起表情，表情面板的高度不对，高端一点的机器就没问题，主要是华为和vivo会出现这种问题

**Comment by YummyLau** [comment]
@Alexxiaopang 你指的是首次弹起吗？ 要输入训练的。后续可以开放用户设置默认值。

**Comment by Alexxiaopang** [comment]
> @Alexxiaopang 你指的是首次弹起吗？ 要输入训练的。后续可以开放用户设置默认值。

就是首次弹起，有时候页面很高，有时候页面很低，但是高端一点的机器就没这个问题

**Comment by YummyLau** [comment]
> > @Alexxiaopang 你指的是首次弹起吗？ 要输入训练的。后续可以开放用户设置默认值。
> 
> 就是首次弹起，有时候页面很高，有时候页面很低，但是高端一点的机器就没这个问题

框架提供的值是我们兼容性测试之后得到的大部分可以兼容的值。但是不排除手机。第一次就直接拉起面板的场景很少见，不过也可以处理的。

**Comment by Alexxiaopang** [comment]
> > > @Alexxiaopang 你指的是首次弹起吗？ 要输入训练的。后续可以开放用户设置默认值。
> > 
> > 
> > 就是首次弹起，有时候页面很高，有时候页面很低，但是高端一点的机器就没这个问题
> 
> 框架提供的值是我们兼容性测试之后得到的大部分可以兼容的值。但是不排除手机。第一次就直接拉起面板的场景很少见，不过也可以处理的。弹过一次输入法之后就正常了。

这个场景应该是不可控的，毕竟聊天窗口，用户一进来，可以先点击表情面板，不可能说限制用户先点击输入框弹出输入法

**Comment by YummyLau** [comment]
@Alexxiaopang 这个建议采纳了。 下个版本支持一下。

**Comment by Alexxiaopang** [comment]
作者可以看一下 https://github.com/FreddyChen/KulaKeyboard 键盘弹出，和你的实现不一样，不过确实这个想法很惊艳，看看有没有可以借鉴的

**Comment by YummyLau** [comment]
@Alexxiaopang 这种做法在以前就实现过了，也是需要软键盘弹出才能获取高度，但是复杂场景popup不太显示，如果是dialog或者popup场景的话。后续我把panelContainer默认没有获取高度的时候默认显示已有布局高度就可以啦。

**Comment by st237688100** [comment]
> @st237688100 v1.3.3 已经兼容了 “导致列表有一部分内容在屏幕之外” 的问题。

厉害了👍，多谢多谢，我去看看具体实现思路。

**Comment by YummyLau** [comment]
@st237688100 新版本也兼容了，我新增了demo，可以看“扩展场景-复杂聊天场景” 或 “api内容容器内部布局干预滑动-内容区域干预子view滑动行为” 都可以。

**Comment by YummyLau** [comment]
@Alexxiaopang v1.3.4 支持设置默认高度，可以通过动画流畅过渡未获取高度前不同高度的功能面板。可见“api 面板扩展及默认高度设置-为获取输入法高度前高度兼容”

**Comment by Alexxiaopang** [comment]
demo里面的虎牙效果，横屏弹出popup后，面板已经变成空的时候，popup不消失

**Comment by Alexxiaopang** [comment]
这好像是个bug，横屏状态下，都有这个问题

**Comment by yyg20101** [comment]
> > 目前panelView应该是和输入法高度一致的，不知道这点我理解是否对。如果是这样，那我上面指的是panelView可以提前指定固定高度(可能ui给个固定值)， panelView高度和输入法不一致的情况。我看微信的表情高度和输入法高度有可能不一样，比如的mi 9se，有虚拟导航栏的时候。
> 
> 你的理解是对的。
> 实际上这个框架就要用来避免面板高度与输入法高度差异所带来的体验问题。 新版本虚拟系统ui也会被动态计算然后这部分高度会还给内容面板。
> 
> 1. 微信表情面板与输入法高度不一致的时候，我的测试机型中有多款体验并不好，一开始是允许的，但是在框架1.0就实现了要自动跟随输入法高度。gif有展示的。
> 2. 基于1问题，所以定的思路是，面板与输入法达到一致高度进而在多个面板中切换保证界面不会跳动，这很重要。因为要考虑多个面板可能存在高度差异，与输入法也存在差异。所以最终的做法是把高度开放给外部监听，让外部根据变动调整panel内部的UI。但是整体的高度是不变的，只能调整内部布局。就像demo一样，拉伸输入法，会让emoji动态调整，如果不要动态调整，就写一个最低的高度然后居中也是可以的。

我也遇到了这个问题，很多手机键盘太特么高了，导致面板内容拉伸严重，有没有办法修改哪里，或者设置，使得面板高度能够固定。。。ui墙裂要特么改

**Comment by YummyLau** [comment]
@yyg20101 v1.3.8 支持

**Comment by lixiongh-hou** [comment]
大佬，最新版本怎么控制第一次打开界面默认不开或者打开软键盘啊

**Comment by YummyLau** [comment]
@lixiongh-hou demo有啦，build的时候传true就默认打开，或者手动调用helper#oKeyboardState()也是可以的。

**Comment by huapeng222** [comment]
大佬，是否可以支持单独的view
我现在项目是用rn写的，我是把聊天这个页面封装成rn原生组件
继承的是RelativeLayout，目前该项目支持activity，dialog。。。好像单纯view的好像不行

**Comment by YummyLau** [comment]
@huapeng222 RN也是支持，支持view级别。

**Comment by YummyLau** [comment]
问题的讨论前往
https://github.com/YummyLau/PanelSwitchHelper/discussions/120
讨论区哦（在Pull requests右侧）。
