### ISSUE TITLE
在Android 5、7、8上有crash，非必现

### ISSUE THREAD

**Issue by WeiLoveWangDan** [YummyLau/PanelSwitchHelper#165]
Fatal Exception: java.lang.IndexOutOfBoundsException
setSpan (-1 ... -1) starts before 0
android.text.SpannableStringInternal.checkRange (SpannableStringInternal.java:442)
android.text.SpannableStringInternal.setSpan (SpannableStringInternal.java:163)
android.text.SpannableStringInternal.setSpan (SpannableStringInternal.java:152)
android.text.SpannableString.setSpan (SpannableString.java:46)
android.text.Selection.setSelection (Selection.java:76)
android.widget.Editor$SelectionModifierCursorController.resetDragAcceleratorState (Editor.java:5911)
android.widget.Editor$SelectionModifierCursorController.resetTouchOffsets (Editor.java:5901)
android.widget.Editor.onFocusChanged (Editor.java:1332)
android.widget.TextView.onFocusChanged (TextView.java:9633)
android.view.View.clearFocusInternal (View.java:6814)
android.view.View.unFocus (View.java:6847)
android.view.ViewGroup.unFocus (ViewGroup.java:1096)
android.view.ViewGroup.unFocus (ViewGroup.java:1096)
android.view.ViewGroup.unFocus (ViewGroup.java:1096)
android.view.ViewGroup.unFocus (ViewGroup.java:1096)
android.view.ViewGroup.unFocus (ViewGroup.java:1096)
android.view.ViewGroup.unFocus (ViewGroup.java:1096)
android.view.ViewGroup.removeViewInternal (ViewGroup.java:5394)
android.view.ViewGroup.removeViewAt (ViewGroup.java:5357)
androidx.recyclerview.widget.RecyclerView$5.removeViewAt (RecyclerView.java:882)
androidx.recyclerview.widget.ChildHelper.removeViewAt (ChildHelper.java:168)
androidx.recyclerview.widget.RecyclerView$LayoutManager.removeViewAt (RecyclerView.java:8639)
androidx.recyclerview.widget.RecyclerView$LayoutManager.scrapOrRecycleView (RecyclerView.java:9209)
androidx.recyclerview.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews (RecyclerView.java:9195)
androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren (LinearLayoutManager.java:630)
androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2 (RecyclerView.java:4134)
androidx.recyclerview.widget.RecyclerView.dispatchLayout (RecyclerView.java:3851)
androidx.recyclerview.widget.RecyclerView.onLayout (RecyclerView.java:4404)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:325)
android.widget.FrameLayout.onLayout (FrameLayout.java:261)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:1791)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1635)
android.widget.LinearLayout.onLayout (LinearLayout.java:1544)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:325)
android.widget.FrameLayout.onLayout (FrameLayout.java:261)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:1791)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1635)
android.widget.LinearLayout.onLayout (LinearLayout.java:1544)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
com.effective.android.panel.view.content.ContentContainerImpl.layoutContainer (ContentContainerImpl.java:360)
com.effective.android.panel.view.content.LinearContentContainer.layoutContainer (LinearContentContainer.java:71)
com.effective.android.panel.view.PanelSwitchLayout.onLayout (PanelSwitchLayout.java:561)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:1791)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1635)
android.widget.LinearLayout.onLayout (LinearLayout.java:1544)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:325)
android.widget.FrameLayout.onLayout (FrameLayout.java:261)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:325)
android.widget.FrameLayout.onLayout (FrameLayout.java:261)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:1791)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1635)
android.widget.LinearLayout.onLayout (LinearLayout.java:1544)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:325)
android.widget.FrameLayout.onLayout (FrameLayout.java:261)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.LinearLayout.setChildFrame (LinearLayout.java:1791)
android.widget.LinearLayout.layoutVertical (LinearLayout.java:1635)
android.widget.LinearLayout.onLayout (LinearLayout.java:1544)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.widget.FrameLayout.layoutChildren (FrameLayout.java:325)
android.widget.FrameLayout.onLayout (FrameLayout.java:261)
com.android.internal.policy.DecorView.onLayout (DecorView.java:960)
android.view.View.layout (View.java:19820)
android.view.ViewGroup.layout (ViewGroup.java:6240)
android.view.ViewRootImpl.performLayout (ViewRootImpl.java:2583)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2299)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1455)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:6963)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:986)
android.view.Choreographer.doCallbacks (Choreographer.java:798)
android.view.Choreographer.doFrame (Choreographer.java:730)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:972)
android.os.Handler.handleCallback (Handler.java:790)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:192)
android.app.ActivityThread.main (ActivityThread.java:6754)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:549)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:828)

**Comment by YummyLau** [comment]
这个堆栈看起来不是框架内部的逻辑哦？
