### ISSUE TITLE
dialogFragment高度变化，布局会错乱是怎么回事

### ISSUE THREAD

**Issue by scatl** [YummyLau/PanelSwitchHelper#19]
具体表现为布局增加内容后，按理说高度会变化，但实际上高度不变，并且布局最下方的内容有一部分不可见，就是新增加的内容将已有内容挤下去了，高度不变。该问题出现在打开了表情面板之后，若从未打开面板不会出现这个问题。
布局中有一个recyclerview（横向），recyclerview初始没有高度，添加item后，整个dialog高度不变，但下方内容（表情按钮等）被挤掉

**Comment by scatl** [comment]
我的dialogFragment不是占满屏幕，是从底部弹出的

**Comment by scatl** [comment]
貌似这种不是占满屏幕的dialogFragment必须把高度写死了才不会出现这种问题

**Comment by YummyLau** [comment]
@scatl 是的，需要填充满，不然计算不到高度的，参考sample就好。
