### ISSUE TITLE
大佬能说下键盘和表情切换的思路吗

### ISSUE THREAD

**Issue by wanglianghai** [YummyLau/PanelSwitchHelper#2]

**Comment by YummyLau** [comment]
> _No description provided._

动态监听输入法唤起后windo界面变化，通过界面变化计算高度差推导出键盘高度。表情切换只是构建一个和输入法一样高度的表情面板。

**Comment by zicen** [comment]
如果只是一个和输入法高度一致的表情面板，显示隐藏的话，我在 DialogFragment 会出现隐藏面板的时候整个对话框下移，然后输入法再将其顶上去的一段动画，这种情况大佬的解决思路是什么？

**Comment by wanglianghai** [comment]
https://gitee.com/wlh520/Emoji 看看这个，就是作者说的那样，我简化了下

**Comment by YummyLau** [comment]
> 如果只是一个和输入法高度一致的表情面板，显示隐藏的话，我在 DialogFragment 会出现隐藏面板的时候整个对话框下移，然后输入法再将其顶上去的一段动画，这种情况大佬的解决思路是什么？

dialog的思路和普通的思路是一样的。PanelSwitchHelper 里面支持dialog模式
