### ISSUE TITLE
提俩小建议

### ISSUE THREAD

**Issue by XuQK** [YummyLau/PanelSwitchHelper#20]
1. 默认的panel高度可给高一点尽量接近键盘的高度，按目前的默认高度，我首次展开panel，如果是表情面板的话，就会被压缩的很惨，显示效果很差。我看现在给的默认高度是198dp，在我的手机上这样的高度是远远不够的，目前我设置的是2/5屏幕高度，感觉还可以。

2. 在从panel面板切换到键盘的时候，面板的消失速度可以稍微延迟一点，比如300ms，而不是点击按钮就立刻消失，然后键盘再弹上来。这样会有一个键盘上来盖在panel上的效果，视觉效果更好一点。

**Comment by YummyLau** [comment]
@XuQK 嗯嗯，你这提议不错，以前那个高度是两年前适配的高度，现在可以根据现有的市场重新评估以下。另外，面板消失延迟效果可以尝试优化下。 后续优化下。

**Comment by YummyLau** [comment]
@XuQK 1.1.0已经更新支持了。可见readMe
