### ISSUE TITLE
Fragment中键盘弹出输入框位置不正确

### ISSUE THREAD

**Issue by LeooooL** [YummyLau/PanelSwitchHelper#22]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
    <include layout="@layout/common_title_layout"></include>
<com.effective.android.panel.view.PanelSwitchLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/panel_switch_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <com.effective.android.panel.view.ContentContainer
        android:id="@+id/content_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:empty_view="@id/empty_view"
        app:edit_view="@id/message_input_et">

        <FrameLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/message_rv"
                android:layout_width="match_parent"
                android:layout_height="match_parent"></androidx.recyclerview.widget.RecyclerView>

            <com.effective.android.panel.view.EmptyView
                android:id="@+id/empty_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent" />
        </FrameLayout>

        <LinearLayout
            android:id="@+id/message_bottom_ll"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:minHeight="50dp"
            android:layout_gravity="bottom">

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:background="@drawable/message_input_bg"
                android:orientation="horizontal">

                <EditText
                    android:id="@+id/message_input_et"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:background="@null"
                    android:textSize="10sp"></EditText>

            </LinearLayout>

            <TextView
                android:id="@+id/send_tv"
                android:layout_width="50dp"
                android:layout_height="match_parent"
                android:layout_marginLeft="8dp"
                android:background="@drawable/message_send_bg"
                android:gravity="center"
                android:text="发送"
                android:textColor="@color/white"
                android:textSize="12sp"></TextView>
        </LinearLayout>

    </com.effective.android.panel.view.ContentContainer>

    <com.effective.android.panel.view.PanelContainer
        android:id="@+id/panel_container"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

    </com.effective.android.panel.view.PanelContainer>
</com.effective.android.panel.view.PanelSwitchLayout>

</LinearLayout>`
![image](https://user-images.githubusercontent.com/11988385/76296552-40154e80-62f1-11ea-98bb-854296022d71.png)
![image](https://user-images.githubusercontent.com/11988385/76296911-ebbe9e80-62f1-11ea-9454-6b3c7473ecb5.png)

手机品牌：一加6T
系统：Android 10.0

请问下在Fragment中使用的时候键盘弹出会导致输入框往上多顶一些距离，没有办法像demo中展示的一样呢。请问是什么原因呢？

**Comment by LeooooL** [comment]
> `
> 
> 
> <com.effective.android.panel.view.PanelSwitchLayout xmlns:android="http://schemas.android.com/apk/res/android"
> xmlns:app="http://schemas.android.com/apk/res-auto"
> android:id="@+id/panel_switch_layout"
> android:layout_width="match_parent"
> android:layout_height="match_parent"
> android:orientation="vertical">
> 
> ```
> <com.effective.android.panel.view.ContentContainer
>     android:id="@+id/content_view"
>     android:layout_width="match_parent"
>     android:layout_height="match_parent"
>     android:orientation="vertical"
>     app:empty_view="@id/empty_view"
>     app:edit_view="@id/message_input_et">
> 
>     <FrameLayout
>         android:layout_width="match_parent"
>         android:layout_height="0dp"
>         android:layout_weight="1">
> 
>         <androidx.recyclerview.widget.RecyclerView
>             android:id="@+id/message_rv"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"></androidx.recyclerview.widget.RecyclerView>
> 
> 
>         <com.effective.android.panel.view.EmptyView
>             android:id="@+id/empty_view"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent" />
>     </FrameLayout>
> 
>     <LinearLayout
>         android:id="@+id/message_bottom_ll"
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:minHeight="50dp"
>         android:layout_gravity="bottom">
> 
>         <LinearLayout
>             android:layout_width="0dp"
>             android:layout_height="match_parent"
>             android:layout_weight="1"
>             android:background="@drawable/message_input_bg"
>             android:orientation="horizontal">
> 
>             <EditText
>                 android:id="@+id/message_input_et"
>                 android:layout_width="match_parent"
>                 android:layout_height="match_parent"
>                 android:layout_weight="1"
>                 android:background="@null"
>                 android:textSize="10sp"></EditText>
> 
>         </LinearLayout>
> 
>         <TextView
>             android:id="@+id/send_tv"
>             android:layout_width="50dp"
>             android:layout_height="match_parent"
>             android:layout_marginLeft="8dp"
>             android:background="@drawable/message_send_bg"
>             android:gravity="center"
>             android:text="发送"
>             android:textColor="@color/white"
>             android:textSize="12sp"></TextView>
>     </LinearLayout>
> 
> </com.effective.android.panel.view.ContentContainer>
> 
> <com.effective.android.panel.view.PanelContainer
>     android:id="@+id/panel_container"
>     android:layout_width="match_parent"
>     android:layout_height="wrap_content">
> 
> 
> </com.effective.android.panel.view.PanelContainer>
> ```
> 
> </com.effective.android.panel.view.PanelSwitchLayout>
> 
> `
> ![image](https://user-images.githubusercontent.com/11988385/76296552-40154e80-62f1-11ea-98bb-854296022d71.png)
> 
> ![微信图片_20200310170022](https://user-images.githubusercontent.com/11988385/76296218-d5641300-62f0-11ea-8edb-cc7cae648d3b.jpg)
> 
> 手机品牌：一加6T
> 系统：Android 10.0
> 
> 请问下在Fragment中使用的时候键盘弹出会导致输入框往上多顶一些距离，没有办法像demo中展示的一样呢。请问是什么原因呢？

![image](https://user-images.githubusercontent.com/11988385/76296816-c5006800-62f1-11ea-83e6-2de7472a2fd1.png)

**Comment by YummyLau** [comment]
这条边看起来是你demo的布局逻辑问题。你可以在ContentContainer加个背景调试下即可。

**Comment by LeooooL** [comment]
问题确认了，使用了侧滑返回Activity框架BGASwipeBackLayout-Android导致的
