### ISSUE TITLE
适配问题 

### ISSUE THREAD

**Issue by AimersCat** [YummyLau/PanelSwitchHelper#23]
不知道大佬有没有做适配，
场景1： 开始没有显示过软键盘：下面输入框显示不全，有一点被遮住了，如果有虚拟按键，虚拟按键就会遮挡输入框
场景2：显示软键盘：输入框距离下面有一段空白距离，如果有虚拟按键，虚拟按键和输入框有一段距离

**Comment by YummyLau** [comment]
@AimersCat 适配了华为等机型的虚拟按键。建议提供了机型/版本我定位下。你说的虚拟按键是否指的是导航栏。另如果能截图的还，麻烦提供了截图更好定位。

**Comment by YummyLau** [comment]
@AimersCat 针对水滴屏，全面屏，挖孔屏，刘海屏等 v1.1.1版本已经修复兼容了。可以更新下版本。
