### ISSUE TITLE
Mi 9 SE 水滴屏手机不兼容

### ISSUE THREAD

**Issue by 121493359** [YummyLau/PanelSwitchHelper#24]
![微信图片_20200327185258](https://user-images.githubusercontent.com/6949503/77749094-690d4180-705c-11ea-845b-fa6147068716.jpg)
怀疑
int screenWithoutNavigationIHeight = PanelHelper.getScreenHeightWithoutNavigationBar(getContext()); 获取的高度在Mi 9 SE上，不包括状态栏高度，造成        
int[] localLocation = PanelHelper.getLocationOnScreen(this);
allHeight -= localLocation[1]; 这里又减去一次状态栏高度。

**Comment by 121493359** [comment]
目前mi 9 se 出现的问题同issue23 所提的场景2

**Comment by YummyLau** [comment]
@121493359 嗯嗯，有刘海的问题已经开始适配了，周末有一个patch。

**Comment by YummyLau** [comment]
@121493359 v1.1.1 版本已经兼容了。可更新

**Comment by 121493359** [comment]
赞
