### ISSUE TITLE
emptyview处理点击收起键盘方式是否不合适？

### ISSUE THREAD

**Issue by 121493359** [YummyLau/PanelSwitchHelper#25]
emptyview 是盖住recyclerview的，如果这样的话recyclerview的内容点击不是响应不了click和longclick事件？im聊天窗口常有点击头像跳转用户信息，长按删除消息等操作

**Comment by YummyLau** [comment]
emptyview只是一个提供的方式，针对你所说的确实是个好建议，v1.1.1版本已经在 activity 场景下完成如何实现 im 的复杂交互。可以长按，也可以点击。可以看看。复杂的场景可以参考，另外，简单的场景可以使用 emptyview 或者 自己调用隐藏也可以。
