### ISSUE TITLE
几个问题请大佬帮忙看下

### ISSUE THREAD

**Issue by AimersCat** [YummyLau/PanelSwitchHelper#27]
<FrameLayout
                    android:layout_width="match_parent"
                    android:layout_height="0dp"
                    android:layout_weight="1">
                    <com.example.demo.chat.CusRecyclerView
                        android:id="@+id/recycler_view"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"/>
                </FrameLayout>

1.demo 里面CusRecyclerView 外层如果被个frameLayout包裹后 设置contentCanScrollOutside（false） 列表就撑不上不去了

2. 还有个就是insert新消息的时候效果不同步,就如新增的item覆盖在上一条消息上，然后上一条消息在往上移，具体情况请用frameLayout包裹CusRecyclerView   然后设置contentCanScrollOutside（true） 看看

感谢大佬！

**Comment by YummyLau** [comment]
@AimersCat 昨晚工作上有些事，今天才有空看到解答下。
1. contentCanScrollOutside api的设计就是用于控制内容区域是否需要滑动上去
2. "新增的item覆盖在上一条消息上，然后上一条消息在往上移" 这个其实和机型动画有关系。我测试了多台设备，小米和华为insert有所差异，demo里面我是默认关闭了item的动画效果的。

针对被 frameLayout 包裹，我需要进一步测试下。

**Comment by YummyLau** [comment]
@AimersCat 刚才有空兼容了下api28的谷歌版本，顺便看了下包裹的问题。
你反馈的这个问题确实存在，虽然固定的模式layout不会到外部，但是内部的height高度并没有及时更新导致的。你切到 1.1.3版本看下，已经做了优化调整。 感谢反馈。

**Comment by AimersCat** [comment]
@YummyLau   
1.新版本framlayout已修复，但是RecyclerView中的内容还没有到可滑动的高度，会把顶部的内容顶上去看不见 这个问题又出现了。
2.请问能否指定RecyclerView撑上去，某些覆盖在RecyclerView上的控件可以不用移动。
3.列表本身没有设置任何动画，但是框架包裹之后，消息插入的动画实在太影响体验了。

感谢大佬！

**Comment by YummyLau** [comment]
@AimersCat 
关于1，你可以自己手动控制是否要顶上去，我demo只是粗略写而已。
关于2，不可以，这种不应该是框架做的。内部只能控制内容面板是否滑动上去。
关于3，之所以包裹之后会出现，是因为包裹之后，recyclerview外部有一层布局，这层布局高度变化的时候，会导致recylerview重复绘制。哪怕不用框架也是会出现这样的效果，这个是系统导致的。建议recyclerview不要嵌套。或者自己定义插入动画就可以了。

**Comment by YummyLau** [comment]
@AimersCat 你这个问题让我 有了一些优化的思路。
weight方案注定会存在一些缺陷。为了解决这个问题，可以考虑把contentContainer后面改成 非线性布局来处理。
