### ISSUE TITLE
输入框默认隐藏,由其他按钮唤出输入框并弹起软键盘,软键盘及表情面板不挤压整体布局,相当于输入框和软键盘面板覆盖在整体布局之上,直播间的效果基本如此

### ISSUE THREAD

**Issue by yemh111** [YummyLau/PanelSwitchHelper#30]

**Comment by YummyLau** [comment]
@yemh111  如果要实现这样的话，直接用 Nothing 模式就可以了，直接覆盖到界面上面，不需要任何处理的。 另外，如果用resize，直播间是从顶部往下绘制的话，不会挤压的。只是输入框底层看不到直播。

**Comment by yemh111** [comment]
> @yemh111 如果要实现这样的话，直接用 Nothing 模式就可以了，直接覆盖到界面上面，不需要任何处理的。 另外，如果用resize，直播间是从顶部往下绘制的话，不会挤压的。只是输入框底层看不到直播。

Nothing模式怎么切换或者设置呢,没有找到处理的地方,我建议可以把文档做的详细些,包括用到的一些属性和设置

**Comment by YummyLau** [comment]
inputMode 为 nothing，窗口检测不到变化无法测量输入法高度的。 针对你的场景，建议使用 popupwindow，参考视频场景下的横屏。其实竖屏也可用的，能做到直接覆盖在界面上面同时输入场景切换可以平滑。 @yemh111

**Comment by yemh111** [comment]
> inputMode 为 nothing，窗口检测不到变化无法测量输入法高度的。 针对你的场景，建议使用 popupwindow，参考视频场景下的横屏。其实竖屏也可用的，能做到直接覆盖在界面上面同时输入场景切换可以平滑。 @yemh111

试过了,没有用,点击输入框,界面内容就会被顶上去

**Comment by YummyLau** [comment]
@yemh111  VideoPopWindow，不会被顶上去的。你可以把布局中的 PanelContainer 的 background 去掉就能看到被盖住的下层布局了。

**Comment by yemh111** [comment]
> @yemh111 VideoPopWindow，不会被顶上去的。你可以把布局中的 PanelContainer 的 background 去掉就能看到被盖住的下层布局了。
你好,我发邮件给你了,希望可以得到帮助,谢谢了

**Comment by YummyLau** [comment]
@yemh111 好的

**Comment by YummyLau** [comment]
@yemh111  加一下我的微信 ： yummyLau
