### ISSUE TITLE
键盘隐藏消失切换时 聊天列表闪烁 内容错位

### ISSUE THREAD

**Issue by br3ant** [YummyLau/PanelSwitchHelper#32]
机型 xiaomi note7 pro
版本1.2.3

PanelSwitchHelper.Builder(this)
                .logTrack(false)
                .contentCanScrollOutside(false)

为了聊天列表不向上移动导致title消失，设置了contentCanScrollOutside = false，但是出现了
键盘隐藏消失切换时 聊天列表闪烁 内容错误的bug

**Comment by YummyLau** [comment]
@br3ant title可以不放到框架内，就不会跟随内容移动的。参考这个布局。
https://github.com/YummyLau/PanelSwitchHelper/blob/master/app/src/main/res/layout/common_chat_with_titlebar_layout.xml

**Comment by br3ant** [comment]
问题解决，🙏
