### ISSUE TITLE
纯Java项目 打包Apk 报错 找不到kotlin.jvm.functions.Function1文件

### ISSUE THREAD

**Issue by zhangzhenduo123** [YummyLau/PanelSwitchHelper#33]
纯Java项目 打包Apk 报错 找不到kotlin.jvm.functions.Function1文件 请问怎么解决

**Comment by YummyLau** [comment]
@zhangzhenduo123 你的as版本是多少，可以配置下gradle中kotlin插件依赖。
后续考虑重新是否为java/kotlin提供不同的库。

**Comment by zhangzhenduo123** [comment]
谢谢您    已经弄好了

**Comment by YummyLau** [comment]
@zhangzhenduo123  嗯嗯，那就好
