### ISSUE TITLE
你好，我是在viewpage中的fragment使用，布局被顶上去

### ISSUE THREAD

**Issue by Alexxiaopang** [YummyLau/PanelSwitchHelper#34]
activity有一块是要固定的 activity的布局是 固定高度的约束ConstraintLayout+viewpage（多个fragment）

 需要输入的fragment内容布局是recyclerview，但是键盘升起来的时候recyclerview全部被顶上去了，会被activity的布局盖住一部分

**Comment by YummyLau** [comment]
@Alexxiaopang 你的场景看起来不是聊天的。你是否是信息流的业务，信息流的业务应该选择dialog或者popup。

**Comment by Alexxiaopang** [comment]
是聊天的，场景是看比赛，然后上面是视频观看，底下是聊天需求，其他tablayout是一些资料，类似于虎牙那种

**Comment by YummyLau** [comment]
你是希望聊天信息被顶上去，但是不要被activity盖住是吧。 初始化的时候，把初始化 helper之前（在build调用前），把这句加上 .contentCanScrollOutside(false)

**Comment by Alexxiaopang** [comment]
非常感谢回复，库里面有很多方法并没有注释或者api没有一个专门的remain，看api方法名字经常理解错误，非常感谢提供这个库

**Comment by YummyLau** [comment]
@Alexxiaopang 下个版本我重新整理一个专门的readme。感谢反馈
