### ISSUE TITLE
内容已经不放在PanelSwitchLayout内了，但是键盘上移的时候，还是挤压

### ISSUE THREAD

**Issue by Alexxiaopang** [YummyLau/PanelSwitchHelper#35]
是tablayout+viewpage的使用

fragment的
布局大致是这样

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <TextView
        android:layout_width="match_parent"
        android:layout_height="60dp"
        android:layout_centerVertical="true"
        android:gravity="center"
        android:text="测试挤压" />

    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:animationSpeed="standard">

在代码里面设置了contentCanScrollOutside
因为希望在收到礼物的时候，礼物是固定不动的，键盘可以盖上去

**Comment by Alexxiaopang** [comment]
经过测试LinearLayout不会被挤压RelativeLayout就会被挤压，但是我的view必须是是盖在recyclerview上面并且居中的，请问有什么办法么？

**Comment by Alexxiaopang** [comment]
根布局是LinearLayout 就不会被挤压了，
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="300dp"
                    android:layout_centerVertical="true"
                    android:gravity="center"
                    android:text="测试挤压" />


    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:animationSpeed="standard">


根布局是RelativeLayout，就一定会被挤压，但是recyclerview不会被挤压变形
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">





    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:animationSpeed="standard">

        
        
        
        <com.effective.android.panel.view.content.ContentRelativeContainer
            android:id="@+id/content_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:relative_edit_view="@id/edit_text">

**Comment by Alexxiaopang** [comment]
根布局是LinearLayout 就不会被挤压了，
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
            <TextView
                android:layout_width="match_parent"
                android:layout_height="300dp"
                android:layout_centerVertical="true"
                android:gravity="center"
                android:text="测试挤压" />

    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:animationSpeed="standard">

        
        
        
        <com.effective.android.panel.view.content.ContentRelativeContainer
            android:id="@+id/content_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:relative_edit_view="@id/edit_text">
根布局是RelativeLayout，就一定会被挤压，但是recyclerview不会被挤压变形
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">
           <TextView
                android:layout_width="match_parent"
                android:layout_height="300dp"
                android:layout_centerVertical="true"
                android:gravity="center"
                android:text="测试挤压" />
    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:animationSpeed="standard">

        
        
        
        <com.effective.android.panel.view.content.ContentRelativeContainer
            android:id="@+id/content_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:relative_edit_view="@id/edit_text">

**Comment by YummyLau** [comment]
contentCanScrollOutside 为true则不会挤压。 你的场景描述得很抽象。礼物是什么布局，贴一下你整体的布局我才能理解你布局是怎么写的。  @Alexxiaopang

**Comment by Alexxiaopang** [comment]
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/ll_root"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">


    <com.effective.android.panel.view.PanelSwitchLayout
        android:id="@+id/panel_switch_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        app:animationSpeed="standard">

        <com.effective.android.panel.view.content.ContentRelativeContainer
            android:id="@+id/content_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:relative_edit_view="@id/edit_text">

            <androidx.recyclerview.widget.RecyclerView
                android:id="@+id/rv_chat"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:paddingBottom="5dp"
                app:layout_behavior="@string/appbar_scrolling_view_behavior"
                tools:itemCount="100"
                tools:listitem="@layout/item_chat_text" />
            <com.puffer.live.ui.widget.roundview.RoundTextView
                android:id="@+id/tv_badge"
                android:layout_width="wrap_content"
                android:layout_height="20dp"
                android:layout_above="@+id/bottom_action"
                android:layout_alignParentBottom="true"
                android:layout_centerHorizontal="true"
                android:layout_marginBottom="5dp"
                android:drawableRight="@mipmap/chatroom_newmessage_remind"
                android:drawablePadding="5dp"
                android:gravity="center"
                android:paddingLeft="10dp"
                android:paddingRight="10dp"
                android:text=""
                android:textColor="@color/colorWhite"
                android:textSize="8sp"
                android:visibility="gone"
                app:rv_backgroundColor="#00B880"
                app:rv_cornerRadius="10dp" />


            <com.puffer.live.ui.tab_match.livedetail.chat.RealNameLinearLayout
                android:id="@+id/bottom_action"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_alignParentBottom="true"
                android:background="#ffffff"
                android:focusable="true"
                android:focusableInTouchMode="true"
                android:gravity="center_vertical"
                android:minHeight="50dp"
                android:orientation="horizontal">

                <ImageView
                    android:id="@+id/emotion_btn"
                    android:layout_width="48dp"
                    android:layout_height="48dp"
                    android:scaleType="centerInside"
                    android:src="@drawable/selector_emotion_btn" />

                <EditText
                    android:id="@+id/edit_text"
                    android:layout_width="0dp"
                    android:layout_height="36dp"
                    android:layout_marginRight="10dp"
                    android:layout_weight="1"
                    android:background="@drawable/linearlayout_background_circle_5_e5e5e5"
                    android:focusable="true"
                    android:focusableInTouchMode="true"
                    android:inputType="textMultiLine"
                    android:paddingLeft="7dp"
                    android:singleLine="false"
                    android:textSize="12sp" />


                <com.sugar.sugarlibrary.widget.StateButton
                    android:id="@+id/bt_send"
                    android:layout_width="54dp"
                    android:layout_height="30dp"
                    android:layout_marginRight="11dp"
                    android:gravity="center"
                    android:text="发送"
                    android:textColor="#ffffff"
                    android:textSize="16sp"
                    android:visibility="gone"
                    app:normalBackgroundColor="@color/color0077FE"
                    app:normalTextColor="@color/colorWhite"
                    app:radius_new="4dp" />

                <com.puffer.live.ui.widget.roundview.RoundTextView
                    android:id="@+id/tv_send"
                    android:layout_width="54dp"
                    android:layout_height="30dp"
                    android:layout_marginRight="11dp"
                    android:gravity="center"
                    android:text="发送"
                    android:textColor="#ffffff"
                    android:textSize="16sp"
                    android:visibility="visible"
                    app:rv_backgroundColor="@color/color0077FE"
                    app:rv_cornerRadius="4dp"
                    app:rv_isRippleEnable="true" />

            </com.puffer.live.ui.tab_match.livedetail.chat.RealNameLinearLayout>


        </com.effective.android.panel.view.content.ContentRelativeContainer>

        <com.effective.android.panel.view.PanelContainer
            android:id="@+id/panel_container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
 <com.effective.android.panel.view.PanelView
                android:id="@+id/panel_emotion"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:panel_layout="@layout/panel_emotion_layout"
                app:panel_trigger="@id/emotion_btn" />



        </com.effective.android.panel.view.PanelContainer>
    </com.effective.android.panel.view.PanelSwitchLayout>


    <TextView
        android:layout_width="match_parent"
        android:layout_height="300dp"
        android:layout_centerInParent="true"
        android:layout_centerVertical="true"
        android:gravity="center"
        android:text="礼物的视图，也只是一个view，希望被键盘盖住而已，相对于整个布局居中" />

</RelativeLayout>

**Comment by Alexxiaopang** [comment]
这个就是全部的布局，外层贴上来就没了，外层是一个RelativeLayout

想做的效果：键盘顶起来的时候是盖住居中的礼物视图（可看做一个textview），但是我用了两种办法，这个视图都会跟着键盘移动

这个是在viewpage的fragment的，activity就一个 固定高度的 RelativeLayout+tablayout+viewpage

**Comment by YummyLau** [comment]
输入法的显示必定会引起 window 窗口的更改，这个是系统特性的。你的问题出在：你的礼物写死了居中根布局，而根布局会随着window变化而更改高度。假如你礼物不想被滑动，也是有办法的。假如在window变化前，你的应用界面是1920高度。变化之后是1120.假设输入法是800，你的礼物视图高度是 900，你在页面初始化之后，获取应用界面高度，然后计算你礼物在没有window变化的时候，marginTop的高度（1920-900）/2 =500，然后动态设置这个属性。就不会跟随window变化而变化。

**Comment by Alexxiaopang** [comment]
可以了，已经解决，因为布局变了，不能用android:layout_centerInParent等属性，我在代码里面动态设置marginTop，已经解决，谢谢！

**Comment by YummyLau** [comment]
@Alexxiaopang 那就好
