### ISSUE TITLE
panelView设置panel_trigger的viewID在另一个pannelView的布局里面，导致第一个panelView无法切换！

### ISSUE THREAD

**Issue by daquanzheng** [YummyLau/PanelSwitchHelper#37]
<com.effective.android.panel.view.PanelContainer
                android:id="@+id/panel_container"
                android:layout_width="match_parent"
                android:layout_height="wrap_content">

                <com.effective.android.panel.view.PanelView
                    android:id="@+id/panel_useful_words"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:panel_layout="@layout/pannel_chat_useful_words_layout"
                    app:panel_toggle="true"
                    app:panel_trigger="@id/tv_useful_words" />

                <com.effective.android.panel.view.PanelView
                    android:id="@+id/panel_edit_words"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:panel_layout="@layout/panel__app_chat_edit_words_layout"
                    app:panel_toggle="true"
                    app:panel_trigger="@id/tv_add" />
            </com.effective.android.panel.view.PanelContainer>
代码如上图所示，第二个PanelView中的tv_add的view是在第一个pannelView中的布局文件layout/pannel_chat_useful_words_layout中。

**Comment by daquanzheng** [comment]
还有一个问题，点击面板中即pannelView中的edittext,弹出的系统键盘会遮挡住此面板，求大佬解决下。之前用过1.0.5版本的库，是不会挡住的。升级到1.2.3之后就出现此问题了。第一个问题我最终用的是重新设置tv_add的点击事件并对面板进行隐藏显示，但效果不是很好。

**Comment by YummyLau** [comment]
@daquanzheng trigger 是内容面板内用于触发panel切换的，强烈建议不能写在另一个panel里面哇。在构建helper的时候，.contentCanScrollOutside(false)  设置这个。  默认是true。

**Comment by daquanzheng** [comment]
trigger这个还比较好解决，当然还是希望能支持pannel内的View可以切换面板，现在主要是第二个问题没法解决，就是pannel内有一个edittext,点击此edittext弹出的系统键盘会遮挡住此pannel。设置contentCanScrollOutside()为false或者true都会出现这个问题。

**Comment by YummyLau** [comment]
@daquanzheng 面板内不应该出现edittext吧。 如果是这样，就不应该设计成面板。设计成panel，那么高度就肯定和输入法高度一致。面板和输入法本身就是互斥显示的。建议不应该用panel实现。

**Comment by daquanzheng** [comment]
@YummyLau 我现在项目的需求就是在面板中有一个添加常用语的按钮，点击按钮切换成另一个面板，然后再第二个面板中输入内容，然后进行保存常用语。这样的需求在之前1.0.5版本是可以实现的，升级之后没法实现了！

**Comment by YummyLau** [comment]
这个需求105应该是实现不了的。或者你添加我微信发一下前后的录屏或截图我定位下。 这个框架输入法和面板设计的初衷用于过度切换，有且仅有一种场景可以显示。

**Comment by daquanzheng** [comment]
@YummyLau 我可以吧我之前1.0.5做好的给你演示一遍，你微信多少，或者你加我微信15825978680.
