### ISSUE TITLE
分屏问题

### ISSUE THREAD

**Issue by genius158** [YummyLau/PanelSwitchHelper#39]
如题

**Comment by YummyLau** [comment]
建议描述下具体问题，方便理解和定位。
部分手机分屏是没有问题的，只是输入法还是在系统窗口下面，体验并不好，pad等大型屏幕机型并没有测试兼容。

**Comment by genius158** [comment]
@YummyLau 不好意思，个人因为之前做个类似的功能，一直没有考虑到分屏，以为你也没有考虑
小米8 MIUI11 只要分屏各种问题

**Comment by YummyLau** [comment]
@genius158 你能描述下具体有哪些问题吗？ 我试了下小米的分屏。除了应用window被缩小，其他的的UI视图表现都复合逻辑。如果应用是在下部分屏幕，表现就和不分屏一直，只是界面高度变小而已。目前并没有专门对上下两屏这种场景去处理的，而华为的分屏是悬浮画中画模式，这种分屏模式是兼容的。

**Comment by YummyLau** [comment]
暂时不处理该场景。
