### ISSUE TITLE
是不是库包没有适配x86的，有些手机弹不出来表情布局

### ISSUE THREAD

**Issue by Alexxiaopang** [YummyLau/PanelSwitchHelper#41]
如题，有些手机弹不出来表情布局，明明是小米手机，但是一直弹出这个com.huawei.android.util.HwNotchSizeUtil

**Comment by Alexxiaopang** [comment]
java.lang.ClassNotFoundException: Didn't find class "android.util.FtFeature" on path: DexPathList[[zip file "/data/app/com.puffer.live.debug-bQcVZwcmJVhcs9akeuw_-g==/base.apk"],nativeLibraryDirectories=[/data/app/com.puffer.live.debug-bQcVZwcmJVhcs9akeuw_-g==/lib/arm64, /data/app/com.puffer.live.debug-bQcVZwcmJVhcs9akeuw_-g==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]

**Comment by YummyLau** [comment]
@Alexxiaopang 这个Log看起来是旧版本的。这部分是通过拦截器尝试获取刘海的，实际上刘海的逻辑在之前的版本中已经去掉啦，只是为了log输出设备的刘海给开发者而已。 确认版本是1.3.1即可。

**Comment by YummyLau** [comment]
@Alexxiaopang x86机型是可以的，没有任何so
