### ISSUE TITLE
1.3.1版本在小米5x手机上测算输入框高度错误。

### ISSUE THREAD

**Issue by zombiu** [YummyLau/PanelSwitchHelper#45]
造成onlayout无限调用，app卡死！

**Comment by YummyLau** [comment]
这个理论上应该是业务监听某个状态重复更改/刷新布局导致的。onLayout 只是用于布局界面。 贴一下log，你打开debug，贴下调用方法的调用链

**Comment by zombiu** [comment]
大佬，我上班再用测试机试试，同样的代码，小米5x面板缩不回来卡死，但是红米7可以！到时候贴log。

**Comment by zombiu** [comment]
我发现在activity中，内容布局滑动时，有一种视觉残留的效果，很怪异，但是fragment中没有！

**Comment by zombiu** [comment]
面板弹出或者收缩时，我发现在activity中，内容布局滑动时，有一种视觉残留的效果，很怪异，但是fragment中没有！

**Comment by YummyLau** [comment]
视觉残留的效果一般是window调整时刷新布局导致的recyclerview 布局错误导致的。可以通过控制刷新时机解决的。下个版本demo完善下。

**Comment by zombiu** [comment]
@YummyLau  大佬，我发现activity如果设置滑动模式的话，就很流畅，但是整个activity连列表没有填充数据的地方都上去了。框架现在支持这种效果吗吗，像fragment一样流畅滑动，如果列表下部有空白时，又不会整个滑动上去。

**Comment by YummyLau** [comment]
@zombiu 目前这种场景是demo里面activity是根据item的个数来手动开启滑动模式的。

**Comment by YummyLau** [comment]
@zombiu 5x上是否还有问题。如果有的话，麻烦你提供一下以下信息：

针对 Bug 的反馈：
Androidx版本：是/否
PanelSwitchHelper版本：v1.3.2
手机型号: 小米5x
手机系统版本： Android 5.0
问题描述：比如 “在xxx场景下输入法无法顶起底部布局”，必要时可提供代码，贴图等。
Log提供：过滤 PanelSwitchLayout，提供异常场景下的 log 信息

**Comment by zombiu** [comment]
> @zombiu 目前这种场景是demo里面activity是根据item的个数来手动开启滑动模式的。

要自己去计算高度对么！

**Comment by zombiu** [comment]
> @zombiu 5x上是否还有问题。如果有的话，麻烦你提供一下以下信息：
> 
> 针对 Bug 的反馈：
> Androidx版本：是/否
> PanelSwitchHelper版本：v1.3.2
> 手机型号: 小米5x
> 手机系统版本： Android 5.0
> 问题描述：比如 “在xxx场景下输入法无法顶起底部布局”，必要时可提供代码，贴图等。
> Log提供：过滤 PanelSwitchLayout，提供异常场景下的 log 信息

大佬 我下午下班 看能不能提上来，太忙了，不好意思！

**Comment by YummyLau** [comment]
> 大佬，我上班再用测试机试试，同样的代码，小米5x面板缩不回来卡死，但是红米7可以！到时候贴log。

@zombiu 小米5x我这边真机测试没有问题。你是否是demo运行。

**Comment by zombiu** [comment]
等大佬的新版本！
