### ISSUE TITLE
小米K30 pro bilibili demo中 键盘没有回收

### ISSUE THREAD

**Issue by lidexin-aldelo** [YummyLau/PanelSwitchHelper#46]
小米K30 pro bilibili demo中 键盘没有回收
小米K30 pro bilibili demo中 键盘没有回收
![Screenshot_2020-06-24-08-54-14-965_com example de](https://user-images.githubusercontent.com/61337272/85484091-b156e400-b5f8-11ea-87c2-534e23d43372.jpg)

**Comment by YummyLau** [comment]
你是Androidxdemo还是非Androidx，我找个机型测试下。 收起应该直接dismiss。

**Comment by YummyLau** [comment]
@lidexin-aldelo 

需要你提供一下反馈信息：
Androidx版本：是/否
PanelSwitchHelper版本：v1.3.2
手机型号: 小米5x
手机系统版本： Android 5.0
问题描述：比如 “在xxx场景下输入法无法顶起底部布局”，必要时可提供代码，贴图等。
Log提供：过滤 PanelSwitchLayout，提供异常场景下的 log 信息

**Comment by lidexin-aldelo** [comment]
Androidx版本：是
PanelSwitchHelper版本：v1.3.2
手机型号: xiaomo k30 pro 
手机系统版本： Android 10   miui 12 
问题描述：问题描述 楼上 
Log提供：这个没有找  等会我在看下
 楼主我一般很少看邮件 所有回复慢了 谅解

**Comment by YummyLau** [comment]
@lidexin-aldelo 我测试了两个红米k30 pro，blbl场景下都是正常的。你的设备输入法是否是自带的/是否设置过系统UI等，也需要提供下。

**Comment by lidexin-aldelo** [comment]
我设置过 
开发者里面 有个dp值
输入法是小米自带的  搜狗输入法小米版

**Comment by YummyLau** [comment]
@lidexin-aldelo 我也试了dp放大和缩小，这个只会影响整体效果。
还是需要你提供无法收回的场景的log，另外，是否设置过autosize

**Comment by YummyLau** [comment]
This issue has not been activated for a long time and is temporarily closed. If you have more questions, please refer to issus again
