### ISSUE TITLE
在CoordinatorLayout应该怎么使用呢?

### ISSUE THREAD

**Issue by zhengjiong** [YummyLau/PanelSwitchHelper#47]
比如说下面这种情况, 底部有一个Edittext, 中间是CoordinatorLayout
<Linearlayout>
<androidx.coordinatorlayout.widget.CoordinatorLayout layout_weight=1>
   <com.google.android.material.appbar.AppBarLayout>
      <com.google.android.material.appbar.CollapsingToolbarLayout>
         .......
      </com.google.android.material.appbar.CollapsingToolbarLayout>
   </<com.google.android.material.appbar.AppBarLayout>
   <recyclerview>
   </recyclerview>
</androidx.coordinatorlayout.widget.CoordinatorLayout>
<EditText>

</EditText>
</LinearLayout>

**Comment by YummyLau** [comment]
非折叠部分放到底部就好。 你这个场景有点特殊，并没有测试过这个场景。后续有问题可以加一下反馈群。
一般IM场景应该不会在折叠布局内。
