### ISSUE TITLE
聊天底部输入区域，如何将发送与加号放在一个位置？

### ISSUE THREAD

**Issue by withyou-zxl** [YummyLau/PanelSwitchHelper#49]
聊天底部输入区域，如何将发送与加号放在一位置
表情面板右侧（发送位置）默认显示加号
输入区域有内容时 显示发送
输入区域无内容时 显示加号

**Comment by YummyLau** [comment]
这个就很多方案了。这部分框架并没有任何约束，放到container底部，最简单就是你用相对布局，两个放到同一个就好了。

**Comment by zombiu** [comment]
@YummyLau  大佬，我添加了一个语音按钮，但是helper的onclick哪里没有添加监听，需要自己手动添加！

**Comment by YummyLau** [comment]
@zombiu viewClick可以监听的你的任何panel触发以及panel的切换。
