### ISSUE TITLE
不会用啊

### ISSUE THREAD

**Issue by najiutan** [YummyLau/PanelSwitchHelper#5]
一定要用dataBinding吗？还有PanelSwitchLayout只能这么布局，不能改？感觉限定的太死了，onStart里面一定要传入这几个布局

**Comment by YummyLau** [comment]
dataBinding只是一种数据绑定工具，可以不用。PanelSwitchLayout里面的布局也可以随意改，onStart传入的是框架需要处理的三个核心布局。里面的布局你随意你填充。 这种方案已经是当前所有类似功能里面做得最灵活的了。

**Comment by najiutan** [comment]
> dataBinding只是一种数据绑定工具，可以不用。PanelSwitchLayout里面的布局也可以随意改，onStart传入的是框架需要处理的三个核心布局。里面的布局你随意你填充。 这种方案已经是当前所有类似功能里面做得最灵活的了。

我代码里面有butterKnife会不会和databinding冲突

**Comment by najiutan** [comment]
我现在有个场景是这样的，输入框是动态创建的，这个输入框不是悬浮在软键盘上面的，但是软键盘上面会悬浮其他的一些按钮，现在的框架支持这种吗？

**Comment by najiutan** [comment]
> dataBinding只是一种数据绑定工具，可以不用。PanelSwitchLayout里面的布局也可以随意改，onStart传入的是框架需要处理的三个核心布局。里面的布局你随意你填充。 这种方案已经是当前所有类似功能里面做得最灵活的了。

好的，谢谢解答

**Comment by YummyLau** [comment]
你可以不用databinding，把datebinding关掉。两者也不会冲突。
其次，你说的场景完全可以支持。ContentContainer 就是用来存放如果输入框或者面板布局没有显示的时的所有业务布局。你的场景输入写在这里里面也是可以的。其次。你要理解这个框架的三个布局是做什么的。ContentContainer 是用来定义 业务布局的，PanelContainer是用来存放你可能切换出来的业务面板。

**Comment by najiutan** [comment]
> 你可以不用databinding，把datebinding关掉。两者也不会冲突。
> 其次，你说的场景完全可以支持。ContentContainer 就是用来存放如果输入框或者面板布局没有显示的时的所有业务布局。你的场景输入写在这里里面也是可以的。其次。你要理解这个框架的三个布局是做什么的。ContentContainer 是用来定义 业务布局的，PanelContainer是用来存放你可能切换出来的业务面板。

好，我先研究研究，不懂再请教，谢谢！

**Comment by YummyLau** [comment]
> > 你可以不用databinding，把datebinding关掉。两者也不会冲突。
> > 其次，你说的场景完全可以支持。ContentContainer 就是用来存放如果输入框或者面板布局没有显示的时的所有业务布局。你的场景输入写在这里里面也是可以的。其次。你要理解这个框架的三个布局是做什么的。ContentContainer 是用来定义 业务布局的，PanelContainer是用来存放你可能切换出来的业务面板。
> 
> 好，我先研究研究，不懂再请教，谢谢！

不客气。

**Comment by najiutan** [comment]
> 你可以不用databinding，把datebinding关掉。两者也不会冲突。
> 其次，你说的场景完全可以支持。ContentContainer 就是用来存放如果输入框或者面板布局没有显示的时的所有业务布局。你的场景输入写在这里里面也是可以的。其次。你要理解这个框架的三个布局是做什么的。ContentContainer 是用来定义 业务布局的，PanelContainer是用来存放你可能切换出来的业务面板。

我看了下库的代码，感觉不支持动态的EditText啊，这个是写在布局里面的，在onFinishInflate里面赋值的，如果我要改成支持动态的话，是不是要弄一个接口设置一个EditText进来呢？

**Comment by YummyLau** [comment]
> > 你可以不用databinding，把datebinding关掉。两者也不会冲突。
> > 其次，你说的场景完全可以支持。ContentContainer 就是用来存放如果输入框或者面板布局没有显示的时的所有业务布局。你的场景输入写在这里里面也是可以的。其次。你要理解这个框架的三个布局是做什么的。ContentContainer 是用来定义 业务布局的，PanelContainer是用来存放你可能切换出来的业务面板。
> 
> 我看了下库的代码，感觉不支持动态的EditText啊，这个是写在布局里面的，在onFinishInflate里面赋值的，如果我要改成支持动态的话，是不是要弄一个接口设置一个EditText进来呢？

不需要。onFinishInflate只是框架为了确保拿得到edittext而已。你在源码级别修改，完全可以自己延后edittext相关逻辑的初始化。同时，确保框架生效的时候，自己保证edittext已经初始化完就可以了。甚至你可以做到动态偷换edittext，能做的事很多很多。

**Comment by najiutan** [comment]
> > > 你可以不用databinding，把datebinding关掉。两者也不会冲突。
> > > 其次，你说的场景完全可以支持。ContentContainer 就是用来存放如果输入框或者面板布局没有显示的时的所有业务布局。你的场景输入写在这里里面也是可以的。其次。你要理解这个框架的三个布局是做什么的。ContentContainer 是用来定义 业务布局的，PanelContainer是用来存放你可能切换出来的业务面板。
> > 
> > 
> > 我看了下库的代码，感觉不支持动态的EditText啊，这个是写在布局里面的，在onFinishInflate里面赋值的，如果我要改成支持动态的话，是不是要弄一个接口设置一个EditText进来呢？
> 
> 不需要。onFinishInflate只是框架为了确保拿得到edittext而已。你在源码级别修改，完全可以自己延后edittext相关逻辑的初始化。同时，确保框架生效的时候，自己保证edittext已经初始化完就可以了。甚至你可以做到动态偷换edittext，能做的事很多很多。

对呀，就是要改变这个eidtText,每次会new出来新的，那是必须改源码是吧，好蛋疼啊

**Comment by YummyLau** [comment]
每次都new？我不太理解你说多的。
或者你可以把你的场景说一下是怎样的。感觉你理解错了。

**Comment by YummyLau** [comment]
每次都new？我不太理解你所说的。
或者你可以把你的场景说一下是怎样的。感觉你理解错了。

**Comment by najiutan** [comment]
> 每次都new？我不太理解你所说的。
> 或者你可以把你的场景说一下是怎样的。感觉你理解错了。

我是在做一个编辑软件，每次会在一个view上面添加新的EditText,每次点击这个EditText的时候会弹出一个输入面板，面板会有其他的功能，这个和你的例子差不多，感觉每次new新的EditText，然后替换你的PanelSwietchHelper里面的东西和监听应该是可以的对吧，我现在正在做这个

**Comment by YummyLau** [comment]
你这个场景很特殊，你可以动态更新ContentContainer里面的edittext。

**Comment by najiutan** [comment]
> 你这个场景很特殊，你可以动态更新ContentContainer里面的edittext。

嗯，谢谢，可以了。还有个问题，有没有什么办法在我build之后，直接就弹出那个键盘出来，弹出软键盘是点击editText才会触发，有没有方法用代码主动触发

**Comment by YummyLau** [comment]
edittext主动请求焦点或者模拟点击，甚至在activity设置 windowSoftInputMode 获取焦点都可以。你可以试试。
