### ISSUE TITLE
小米4底部布局有时无法被输入法顶起。demo也会出现

### ISSUE THREAD

**Issue by raoguanhui** [YummyLau/PanelSwitchHelper#50]

**Comment by YummyLau** [comment]
@raoguanhui 
麻烦你提供一下以下信息：

针对 Bug 的反馈：
Androidx版本：是/否
PanelSwitchHelper版本：v1.3.2
手机型号: 小米5x
手机系统版本： Android 5.0
问题描述：比如 “在xxx场景下输入法无法顶起底部布局”，必要时可提供代码，贴图等。
Log提供：过滤 PanelSwitchLayout，提供异常场景下的 log 信息

**Comment by raoguanhui** [comment]
Androidx版本：否
PanelSwitchHelper版本：v1.3.2
手机型号: 小米4 
手机系统版本： Android 6.0.1
问题描述：最新demo仿朋友圈评论无法顶起底部布局
Log提供：
06-28 15:10:26.754 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 contentContainer : height - 1860
06-28 15:10:26.754 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 1080 b : 1860
06-28 15:10:26.754 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 panelContainerTop : height - 764
06-28 15:10:26.754 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 panelContainer :  l : 0  : 1860 r : 1080 b : 2624
06-28 15:10:26.839 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onGlobalLayout => screenHeight : 1920, contentHeight : 1096，systemUIHeight : 60
06-28 15:10:26.839 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onGlobalLayout => keyboardHeight is : 764, isShow : false
06-28 15:10:26.840 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onGlobalLayout => screenHeight : 1920, contentHeight : 1096，systemUIHeight : 60
06-28 15:10:26.840 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onGlobalLayout => keyboardHeight is : 764, isShow : false
06-28 15:10:26.841 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onGlobalLayout => screenHeight : 1920, contentHeight : 1096，systemUIHeight : 60
06-28 15:10:26.841 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onGlobalLayout => keyboardHeight is : 764, isShow : false
06-28 15:10:26.863 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  onLayout(changed : true , l : 0  , t : 0 , r : 1080 , b : 1096） ===================&&&&=================
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  切换模式  :滑动模式
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  当前状态  :收起所有输入源
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  是否是全屏  ：false
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  是否是pad机型  ：false
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  是否显示导航栏  ：false
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  是否是竖屏  ：true
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  界面高度（包含系统UI）  ：1920
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1920
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  界面高度（不包含系统UI，动态计算）  ：1096
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  刘海高度  ：  0
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  toolbar高度  ：0
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  StatusBar高度  ：60
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  NavigationBar高度  ：130
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，60）
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  PanelSwitchLayout paddingTop  ：0
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  输入法高度  ：764
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  内容容器 top  ：0
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  内容容器 高度 ：1860
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  面板容器 top ：1860
06-28 15:10:26.864 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  面板容器 高度 764
06-28 15:10:26.865 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 contentContainer : height - 1860
06-28 15:10:26.865 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 1080 b : 1860
06-28 15:10:26.865 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 panelContainerTop : height - 764
06-28 15:10:26.865 14518-14518/com.example.demo D/LogTracker: PanelSwitchLayout#onLayout =>  layout参数 panelContainer :  l : 0  : 1860 r : 1080 b : 2624

**Comment by YummyLau** [comment]
@raoguanhui 看起来参数是没有问题的，你这个手机的性能是否是很低。 你可以通过显示dialog之后，post一个runnable延迟手动调用toKeyboardState来解决。 我在低性能手机上也遇到这个问题。

**Comment by raoguanhui** [comment]
是指在FeedCommentDialog的show() 方法中，延迟调用helper.toKeyboardState();？？？
