### ISSUE TITLE
recyclerview没有到可滑动的高度时，会被顶上去看不见，我看已关闭的issue里提示已经解决了，不知道哪里有问题

### ISSUE THREAD

**Issue by ender115** [YummyLau/PanelSwitchHelper#52]
作者您好
我现在recyclerview没有到可滑动的高度时，会被顶上去看不见，我看已关闭的issue里提示已经解决了，不知道哪里有问题。
我是在fragment里面使用的，基本上是参照DEMO里面的聊天场景(Fragmeng):自定义标题栏来写的，布局如下：
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@color/color_f2f3f6">

    <com.effective.android.panel.view.PanelSwitchLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">

        
        
        
        <com.effective.android.panel.view.content.LinearContentContainer
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            app:linear_edit_view="@id/et_input_panel">

            <com.dengta.date.view.HookActionUpRecyclerView
                android:id="@+id/rv_group_message_content"
                android:layout_width="match_parent"
                android:layout_height="0dp"
                android:layout_weight="1"/>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:paddingTop="@dimen/sw_dp_1"
                android:paddingBottom="@dimen/sw_dp_2"
                android:background="@drawable/chat_bottom_input_bg_shape">

                <ImageView
                    android:id="@+id/iv_input_panel_voice_keyboard"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom"
                    android:paddingLeft="@dimen/sw_dp_5"
                    android:paddingTop="@dimen/sw_dp_5"
                    android:paddingRight="@dimen/sw_dp_5"
                    android:paddingBottom="@dimen/sw_dp_9"
                    android:layout_marginStart="@dimen/sw_dp_3"
                    android:src="@drawable/chat_voice" />

                <RelativeLayout
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center_vertical"
                    android:layout_marginStart="@dimen/sw_dp_3"
                    android:layout_marginTop="@dimen/sw_dp_4"
                    android:layout_marginBottom="@dimen/sw_dp_4"
                    android:layout_weight="1"
                    android:gravity="center">

                    <EditText
                        android:id="@+id/et_input_panel"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:background="@drawable/gray_line_white_big_shape"
                        android:maxLines="3"
                        android:hint="@string/session_msg_input_hint"
                        android:paddingStart="@dimen/sw_dp_8"
                        android:paddingEnd="@dimen/sw_dp_4"
                        android:paddingTop="@dimen/sw_dp_4"
                        android:paddingBottom="@dimen/sw_dp_4"
                        android:focusableInTouchMode="true"
                        android:minHeight="@dimen/sw_dp_32"
                        android:textColor="@color/black_pale"
                        android:textSize="@dimen/sw_dp_12"
                        android:visibility="visible" />

                    <Button
                        android:id="@+id/btn_input_panel_voice"
                        style="?android:attr/borderlessButtonStyle"
                        android:layout_width="match_parent"
                        android:layout_height="@dimen/sw_dp_32"
                        android:background="@drawable/gray_line_gray_bg_fifteen_shape"
                        android:text="@string/hold_talk"
                        android:textColor="@color/black_pale"
                        android:textSize="@dimen/sw_dp_12"
                        android:visibility="gone"
                        tools:visibility="gone" />
                </RelativeLayout>

                <ImageView
                    android:id="@+id/iv_input_panel_emoji"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom"
                    android:paddingStart="@dimen/sw_dp_8"
                    android:paddingTop="@dimen/sw_dp_5"
                    android:paddingEnd="@dimen/sw_dp_5"
                    android:paddingBottom="@dimen/sw_dp_9"
                    android:src="@drawable/emoji_iv_selector" />

                <ImageView
                    android:id="@+id/iv_input_panel_add"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom"
                    android:paddingLeft="@dimen/sw_dp_2"
                    android:paddingTop="@dimen/sw_dp_5"
                    android:paddingRight="@dimen/sw_dp_5"
                    android:paddingBottom="@dimen/sw_dp_9"
                    android:src="@drawable/chat_add" />

                <Button
                    android:id="@+id/btn_input_panel_send"
                    style="?android:attr/borderlessButtonStyle"
                    android:layout_width="@dimen/sw_dp_28"
                    android:layout_height="@dimen/sw_dp_20"
                    android:layout_gravity="bottom"
                    android:layout_marginRight="@dimen/sw_dp_4"
                    android:layout_marginBottom="@dimen/sw_dp_5"
                    android:background="@drawable/nim_message_button_bottom_send_selector"
                    android:gravity="center"
                    android:text="@string/send"
                    android:textColor="@color/white"
                    android:textSize="@dimen/sw_dp_8"
                    android:visibility="gone" />
            </LinearLayout>
        </com.effective.android.panel.view.content.LinearContentContainer>

        
        <com.effective.android.panel.view.panel.PanelContainer
            android:id="@+id/panel_container"
            android:layout_width="match_parent"
            android:layout_height="wrap_content">

            
            
            
            
            <com.effective.android.panel.view.panel.PanelView
                android:id="@+id/panel_emotion"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:panel_layout="@layout/layout_panel_emotion"
                app:panel_trigger="@id/iv_input_panel_emoji" />

            <com.effective.android.panel.view.panel.PanelView
                android:id="@+id/panel_addition"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:panel_layout="@layout/layout_panel_add"
                app:panel_trigger="@id/iv_input_panel_add" />

        </com.effective.android.panel.view.panel.PanelContainer>
    </com.effective.android.panel.view.PanelSwitchLayout>

    <include layout="@layout/layout_voice_record" />
</FrameLayout>

**Comment by ender115** [comment]
Androidx版本：是
PanelSwitchHelper版本：v1.3.0

**Comment by ender115** [comment]
请问下，是需要设置contentCanScrollOutside(false)
然后再设置
if(mAdapter.getItemCount() > 10){
                    mHelper.scrollOutsideEnable(true);
                }
这样么？我这样设置后是没有问题的。但是聊天内容很多种消息类型，不能确定10条刚好满屏。
然后通过mBinding.recyclerView.canScrollVertically(-1)去判断的话也是有点体验不好
不知道作者有没有更好的办法可以指导一下，谢谢

**Comment by YummyLau** [comment]
@ender115 嗯是需要动态开启的。 有个思路你可以实时，在recyclerview静止的获取，获取最后一个holder，如果当前holder是完全显示的，则默认还没有满屏。判断是否完全显示可通过获取可视化矩阵的api来判断。

**Comment by ender115** [comment]
好的，谢谢，另外总感觉弹出键盘recyclerview网上顶的时候里面的item有点卡卡的，就算post延迟一下还是会有点卡卡的

**Comment by YummyLau** [comment]
@ender115 可以尝试升级下1.3.2.

**Comment by ender115** [comment]
嗯，感觉好一些了，正在做聊天界面，再次感谢作者的分享

**Comment by YummyLau** [comment]
> 嗯，感觉好一些了，正在做聊天界面，再次感谢作者的分享

嗯，可以添加到交流反馈群随时反馈。
