### ISSUE TITLE
如何控制直接打开表情的面板

### ISSUE THREAD

**Issue by huanghaoming** [YummyLau/PanelSwitchHelper#54]
看到有直接打开键盘面板的。。toKeyboardState。。。。有没有类似toEmotionState

**Comment by YummyLau** [comment]
@huanghaoming performClick 你的表情键就可以了...

**Comment by huanghaoming** [comment]
我试了一下。。。用performClick打开。。 表情 面板是空白透明的

**Comment by huanghaoming** [comment]
我是在dialogfragment使用的。。。。
 emotion_btn.post(new Runnable() {
            @Override
            public void run() {
                emotion_btn.performClick();
            }
        });

要这样才可以。。。。。
