### ISSUE TITLE
1.3.2.1版本如果第一次弹出的是面板，高度不对，比软键盘弹出时高度不对。

### ISSUE THREAD

**Issue by zombiu** [YummyLau/PanelSwitchHelper#55]
大佬，第一次弹面板的高度，是怎么算的，我看了半天没整明白！

**Comment by YummyLau** [comment]
@zombiu 第一次是默认高度。要键盘出来“训练”之后，以后就会和键盘一致。

**Comment by zombiu** [comment]
@YummyLau  我看以前的版本不需要训练啊，这个大佬能不想想办法！

**Comment by YummyLau** [comment]
@zombiu 要的，除非你弹出过输入法。这种场景已经有方案优化了，你只要弹出过输入法以后才能获取到正确高度。

**Comment by zombiu** [comment]
@YummyLau  大佬 野火im的软键盘第一次面板弹框可以正确获取高度，不过我没看懂，大佬可以借鉴下！

**Comment by YummyLau** [comment]
> @YummyLau 大佬 野火im的软键盘第一次面板弹框可以正确获取高度，不过我没看懂，大佬可以借鉴下！

嗯嗯，有方案啦。
