### ISSUE TITLE
empty_view设置可见时，首次进入列表无法滑动

### ISSUE THREAD

**Issue by caihuanjian** [YummyLau/PanelSwitchHelper#6]
1、empty_view设置可见时，首次进入列表无法滑动
2、软键盘出现时，滑动聊天列表，这个时候事件被empty_view吃掉了，没法滑动，离开屏幕，软键盘收起来。体验有点不舒服。微信体验是：软键盘出现时，不影响列表滑动，列表滑动自动收起软键盘。

能否提供一个收起面板和软键盘的方法...

**Comment by YummyLau** [comment]
@caihuanjian 
1. empty_view 会被框架处理成不可见的，你的可见场景是什么，可以描述下吗？
2. 针对微信出现软键盘可以滑动，这个比较简单，可以通过不消费move事件处理，因为不针对所有内容列表是聊天列表，所以我没有特别处理，后面feature可以添加选择项。
3. helper有一个 resetState的方法可以收起面板和软键盘。

**Comment by YummyLau** [comment]
@caihuanjian 新增了 EmptyView，没有打成jar。你可以试试，在panle/view/EmptyView目录下。如果需要jar我可以单独发一个版本支持。

**Comment by YummyLau** [comment]
使用1.0.2版本即可。库进行升级更新，相对应的sample也更新了，概要可以看readme

**Comment by caihuanjian** [comment]
empty_view我确实不需要设置成可见的，框架应该在初始化这个view 的时候就设置为不可见，以防像我这样的一开始没在xml 设置gone属性，首次进入就会滑动不了列表的情况

**Comment by YummyLau** [comment]
> empty_view我确实不需要设置成可见的，框架应该在初始化这个view 的时候就设置为不可见，以防像我这样的一开始没在xml 设置gone属性，首次进入就会滑动不了列表的情况
嗯嗯，感谢反馈。新版本1.0.2更新了逻辑并优化empty_view的事件处理，从事件的传递源处彻底处理了。

**Comment by caihuanjian** [comment]
老哥能加个微信让我膜拜下吗？

**Comment by YummyLau** [comment]
> 老哥能加个微信让我膜拜下吗？

这个是我的微信。pursuit_of_720，有问题可以加这个找我
