### ISSUE TITLE
下载demo 运行 朋友圈效果 点击评论 输入框被键盘遮挡 一加6T

### ISSUE THREAD

**Issue by joker-fu** [YummyLau/PanelSwitchHelper#60]

**Comment by YummyLau** [comment]
@joker-fu 贴上log你就是最靓的仔

Androidx版本：是/否
PanelSwitchHelper版本：v1.3.2
手机型号: 小米5x
手机系统版本： Android 5.0
问题描述：比如 “在xxx场景下输入法无法顶起底部布局”，必要时可提供代码，贴图等。
Log提供：过滤 PanelSwitchLayout，提供异常场景下的 log 信息
由于机型反馈的问题很多都是机型兼容/开发者API使用不当导致的，定位问题比较难。

**Comment by joker-fu** [comment]
就是你的demo

手机型号: 一加6T 
手机系统版本： Android 10
问题描述：朋友圈效果 点击评论 输入框被键盘遮挡

**Comment by YummyLau** [comment]
@joker-fu 刚过了兼容测试。专门测试了6T，我这里是正常的。你的手机更改过哪些系统设置吗？ 

建议clone下项目，跑一下。如果出现改场景提供下log信息。

**Comment by YummyLau** [comment]
[参考这个issue](https://github.com/YummyLau/PanelSwitchHelper/issues/63)
