### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by 330676687** [YummyLau/PanelSwitchHelper#61]
使用最新1.3.2.1版本 初始化后返回出现内存泄漏问题
![Screenshot_2020-07-03-08-14-30-847_com z tzrl1](https://user-images.githubusercontent.com/13881479/86419601-38e1d880-bd06-11ea-9602-13c64b247600.png)

**Comment by YummyLau** [comment]
@330676687 Androidx的demo场景用 leakcanary 2.4 重复测试了几遍并没有泄漏的问题。
你反馈的是Demo还是继承之后的项目，具体得看你的场景代码才能定位问题。

```
Watching instance of androidx.fragment.app.FragmentManagerViewModel (androidx.fragment.app.FragmentManagerViewModel received ViewModel#onCleared() callback) with key e0b94103-8dbc-4198-a48f-6022ab0c81bb
Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 875aab56-5909-47ee-8f1e-725911c99a66
Watching instance of androidx.lifecycle.ReportFragment (androidx.lifecycle.ReportFragment received Fragment#onDestroy() callback) with key d8198a40-aded-495d-bfde-208329718409
Watching instance of com.example.demo.scene.chat.ChatActivity (com.example.demo.scene.chat.ChatActivity received Activity#onDestroy() callback) with key 555e1b03-8ac7-4a64-98bc-cf5439f9ab1f
Scheduling check for retained objects because found new object retained
Scheduling check for retained objects because found new object retained
Ignoring request to check for retained objects (found new object retained), already scheduled in -1ms
Ignoring request to check for retained objects (found new object retained), already scheduled in -1ms
Check for retained object found no objects remaining
Check for retained object found no objects remaining
```

**Comment by 330676687** [comment]
我用的是google的navigation库，你可以试一下

**Comment by 330676687** [comment]
@YummyLau 猜测框架是在activity销毁里做的释放，但是navigation需要在fragment销毁的时候释放

**Comment by YummyLau** [comment]
@330676687 根据你的描述，问题大概已经定位到了。
demo中每个activity有一个独立的fragment。fragment销毁的时候activity随着销毁，leak 在计算retained 的时候感知不到fragment的泄漏。如果出现多个平行的fragment在pager等容器内，activity生命周期远大于fragment时，可能会泄漏，泄漏的原因是 activity#window.rootView.viewTreeObserver 持有fragment#PanelSwitchLayout里面的内部类，导致fragment内的PanelSwitchLayout无法被回收进而无法回收fragment。
这个问题已经修复，会在下个版本发布。

**Comment by YummyLau** [comment]
@DoNotLookAtMe v1.3.3 修复

**Comment by 330676687** [comment]
试了下，返回上一个界面正常销毁，但是跳转下个界面问题依然存在
navigation返回上个界面走的onDestroyView和onDestroy，跳转下个界面只走onDestroyView

**Comment by YummyLau** [comment]
只有会销毁view，window就会解绑不再引用fragment，window不会泄漏的。  “下个界面只走onDestroyView” 不太理解你说说的，能否描述进一步描述下。 泄漏只会出现在返回上层而当层无法回收。如果往下层走，这些都在stack栈里的。

**Comment by 330676687** [comment]
navigation库切换界面是用的replace 所以A到B的话A会走OnDestroyView周期

**Comment by YummyLau** [comment]
@330676687 可以加一下我微信，方便理解你的场景。

**Comment by YummyLau** [comment]
针对 navigation 只回调 OnDestroyView 手动设置view和helper引用为空。
