### ISSUE TITLE
可以提供方法直接展示特定的PanelView 

### ISSUE THREAD

**Issue by DoNotLookAtMe** [YummyLau/PanelSwitchHelper#65]
公开一个方法调用checkoutPanel（id）

**Comment by YummyLau** [comment]
@DoNotLookAtMe 之前有考虑的，不过由于都是调触发器view 的点击触发的，外层业务直接调用 view.performClick 就好了。

**Comment by YummyLau** [comment]
@DoNotLookAtMe v1.3.3 支持
