### ISSUE TITLE
contentCanScrollOutside方法

### ISSUE THREAD

**Issue by 330676687** [YummyLau/PanelSwitchHelper#66]
为什么最新1.3.3版本删除了该方法，我这边类似朋友圈评论的需求需要使用固定模式来计算位置

**Comment by YummyLau** [comment]
@330676687 固定模式会动态修改高度，会有比较大的缺陷的。新版本朋友圈评论也是支持的。你的计算位置指的是？

**Comment by 330676687** [comment]
我是直接把view写在fragment的布局里的 在1.3.2.1因为是固定模式 计算距离不会受到影响
demo里是用的dialog 但是这样的话就不能滑动同时隐藏了 体验不好

**Comment by YummyLau** [comment]
@330676687 其实写在fragment也是可以的，同时滑动和隐藏，你应该用auto_reset的api的。
你的计算距离没有说为了什么？固定模式是会动态更高content高度，这个做动画不友好。
可以加一下我微信。
