### ISSUE TITLE
如果EditText封装在View里面怎么使用

### ISSUE THREAD

**Issue by lannaican** [YummyLau/PanelSwitchHelper#69]
因为输入框是比较复杂的View需要封装

**Comment by YummyLau** [comment]
写你自定义view里面里 xml 中 edittext 布局id。 @lannaican

**Comment by lannaican** [comment]
在Activity和Fragment中使用，打开页面输入框都会慢慢撑满整个布局，请问是什么问题？

**Comment by YummyLau** [comment]
> 输入框

DEMO吗？ 没遇到过这个问题，可以提供截图或描述下场景。
