### ISSUE TITLE
app:edit_view="@id/edit_text"             app:empty_view="@id/empty_view"无法使用

### ISSUE THREAD

**Issue by najiutan** [YummyLau/PanelSwitchHelper#7]
我用module方式导入之后，在主工程布局文件引用这两个属性提示：
pp/src/main/res/layout/activity_main.xml:15: AAPT: error: attribute edit_view (aka com.ljt.keyboard:edit_view) not found.

**Comment by najiutan** [comment]
是我没有引入，犯了低级错误

**Comment by YummyLau** [comment]
ok，没什么问题issue我关了。
