### ISSUE TITLE
当对话只有一行时，recyclerView没有看到第一次聊天发的信息，整体移上去了？

### ISSUE THREAD

**Issue by JackLiaoJH** [YummyLau/PanelSwitchHelper#71]
当对话只有一行时，recyclerView没有看到第一次聊天发的信息，整体移上去了？

**Comment by JackLiaoJH** [comment]
关掉吧，我看到了其他也有人问了

**Comment by YummyLau** [comment]
@JackLiaoJH demo没仔细看哦，要批评下

**Comment by lannaican** [comment]
按照Demo中通过addContentScrollMeasurer来控制Recyclerview的滚动距离，但是如果这样的话如果数据满屏，在输入法显示的情况下就看不到recyclerview最上面的数据了，这个怎么办？ @YummyLau

**Comment by lannaican** [comment]
我试着在getScrollDistance给recyclerview加上paddingTop可以解决，我需要根据收缩还是展开状态来区分是否需要padding值，但是无法知道当前状态是展开还是收缩

**Comment by lannaican** [comment]
我试着在addPanelChangeListener->onNone中还原paddingTop，在getScrollDistance设置paddingTop，基本可以解决，但是效果并不好

**Comment by YummyLau** [comment]
@lannaican addContentScrollMeasurer 用来控制滑动模式下的内容布局内的子布局滑动。如果你不想滑动，返回0就不会滑动。满屏向上滑动是正常交互，微信也是如此。不满屏则需要动态返回滑动距离。demo中有演示。

**Comment by lannaican** [comment]
> @lannaican addContentScrollMeasurer 用来控制滑动模式下的内容布局内的子布局滑动。如果你不想滑动，返回0就不会滑动。满屏向上滑动是正常交互，微信也是如此。不满屏则需要动态返回滑动距离。demo中有演示。不建议设置paddingTop，这样会导致先上滑动又往下调整，应该一步到位。

是的，我的问题是满屏向上滑动后recyclerview看不到最前面的项，Demo中通过滑动事件隐藏输入法来规避了这个问题，我看QQ的效果也是这样

**Comment by YummyLau** [comment]
看你的描述你的满屏指的是布局填充满父容器而不是说列表中item内容是满的。
任何场景都可以通过 addContentScrollMeasurer 来控制滑动距离的，只要你业务场景计算得准确就好了。

**Comment by lannaican** [comment]
> 看你的描述你的满屏指的是布局填充满父容器而不是说列表中item内容是满的。
> 任何场景都可以通过 addContentScrollMeasurer 来控制滑动距离的，只要你业务场景计算得准确就好了。 @lannaican

我指的是item满屏，我说具体些，addContentScrollMeasurer是改变布局位置，当满屏的时候列表布局被顶起，这时候列表头部超过可视范围，于是就看不到顶部item，不知道这样描述清晰吗

**Comment by YummyLau** [comment]
@lannaican 微信如此哦 。你面板/软键盘显示，整体布局会向上移动。
