### ISSUE TITLE
横屏状态下，面板的很多监听都不起效果，输入法隐藏后，还显示空白面板

### ISSUE THREAD

**Issue by Alexxiaopang** [YummyLau/PanelSwitchHelper#74]
可见demo的虎牙，哔哩哔哩等popup，点击空白处，键盘消失但是还显示空白面板
监听键盘还有pannel的方法也没有走

**Comment by Alexxiaopang** [comment]
机型，小米9，华为mate9等，log并没有特别的输出，我明天录一个视频
你可以试多几次，横屏之后，多点几次旁边空白，然后弹起来收起键盘，基本都能出现，小米手机百分百，华为手机是多几次就出现了





------------------ 原始邮件 ------------------
发件人: YummyLau <notifications@github.com&gt;
发送时间: 2020年7月15日 18:57
收件人: YummyLau/PanelSwitchHelper <PanelSwitchHelper@noreply.github.com&gt;
抄送: Alexxiaopang <610611029@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[YummyLau/PanelSwitchHelper] 横屏状态下，面板的很多监听都不起效果，输入法隐藏后，还显示空白面板 (#74)

**Comment by Alexxiaopang** [comment]
复现视频地址：
https://share.weiyun.com/0RxVPo2w
视频中是Demo APP，没修改任何内容，小米手机可以百分百重现，华为手机操作几次弹起收起来也会复现
谢谢大佬，希望可以修复这个bug，打扰了





------------------ 原始邮件 ------------------
发件人: YummyLau <notifications@github.com&gt;
发送时间: 2020年7月15日 18:57
收件人: YummyLau/PanelSwitchHelper <PanelSwitchHelper@noreply.github.com&gt;
抄送: Alexxiaopang <610611029@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[YummyLau/PanelSwitchHelper] 横屏状态下，面板的很多监听都不起效果，输入法隐藏后，还显示空白面板 (#74)





 
@Alexxiaopang 目前没遇到过。贴一下对应log和备注下机型信息。

**Comment by YummyLau** [comment]
@Alexxiaopang 你是否开启了系统旋转。另外，你小米设备底部有个全局手势栏，怎么设置的。

**Comment by YummyLau** [comment]
> @Alexxiaopang 你是否开启了系统旋转。另外，你小米设备底部有个全局手势栏，怎么设置的。MIUI多少，提供一下小米的设备信息。

**Comment by Alexxiaopang** [comment]
开启了系统旋转的，那个全局手势栏是miui12自带的（只是显示的一个小块）
空白布局在模拟器上也是可以重现的，横屏状态下切换一下表情和键盘，后面也是和视频一样了

**Comment by Alexxiaopang** [comment]
设备：
小米9，系统：miui12最新稳定版
华为荣耀9X，mate8，系统：Emui都是9
As自带模拟器，android10

**Comment by YummyLau** [comment]
@Alexxiaopang 已修复。晚点更新包体。

**Comment by Alexxiaopang** [comment]
那我可以先按照现在的布局么？后面等你更新之后直接升级，因为项目要用，感谢了

**Comment by YummyLau** [comment]
@Alexxiaopang 经过定位之后，发现这个不是库带来的影响。
其实是因为库内部严格控制布局的layout，而你popupwindow/dialog demo中监听了 none状态下dismiss会导致即将onLayout的布局消失了。demo内是复用的场景，你去除复用就可以了。已经有方案处理了，

**Comment by Alexxiaopang** [comment]
但是小米手机并没有直接复用，一进去就会出现这个问题，其他手机需要操作一两次才会有这个问题
坐等发版，感谢了，项目急用

**Comment by YummyLau** [comment]
@Alexxiaopang ok

**Comment by YummyLau** [comment]
> 但是小米手机并没有直接复用，一进去就会出现这个问题，其他手机需要操作一两次才会有这个问题
> 坐等发版，感谢了，项目急用
小米并没有复用？ 出现什么问题。目前我这里的兼容测试从小米6-10，全部都没有问题。

**Comment by Alexxiaopang** [comment]
> > 但是小米手机并没有直接复用，一进去就会出现这个问题，其他手机需要操作一两次才会有这个问题
> > 坐等发版，感谢了，项目急用
> > 小米并没有复用？ 出现什么问题。目前我这里的兼容测试从小米6-10，全部都没有问题。

没有其他问题，就最开始的问题，感谢回复

**Comment by YummyLau** [comment]
@Alexxiaopang 你提供的视频里面没有bilibiili的。。抖音的demo是没有支持横屏的。你测试下bilibili的场景，应该是可以的 。

**Comment by Alexxiaopang** [comment]
不复用华为是可以的，但是小米的miui12还是不行
哔哩哔哩也是不行，如果需要消失，必须点两下表情面板
小米9 miui12 复现视频（视频中app纯demo下载编译，没做修改）：
https://share.weiyun.com/1jFI1EkN

**Comment by Alexxiaopang** [comment]
我去设置把miui12 默认打开的小白条关闭然后去除复用就可以了，但是这个白条是miui12自动打开的，这个就比较难搞了

**Comment by Alexxiaopang** [comment]
所以miui12横屏（有底部条）会出现问题，这个估计比较棘手

**Comment by YummyLau** [comment]
> 所以miui12横屏（有底部条）会出现问题，这个估计比较棘手

已经适配了。你加我微信吧，我给你先行的demo验证。

**Comment by Alexxiaopang** [comment]
好的，已发送请求，感谢
