### ISSUE TITLE
聊天背景上移

### ISSUE THREAD

**Issue by xchdong** [YummyLau/PanelSwitchHelper#75]
聊天页面设置图片背景，软键盘显示，背景会上移。怎么样可以让背景固定不动？

**Comment by YummyLau** [comment]
@xchdong 背景可以放到外层。自由控制就可以了。

**Comment by VeerHan** [comment]
> @xchdong 背景可以放到外层。自由控制就可以了。

可以提供一个demo吗？ 试了一下还是不行
