### ISSUE TITLE
弹起来的时候，是否可以手动指定显示某个面板PanelView

### ISSUE THREAD

**Issue by tt905** [YummyLau/PanelSwitchHelper#77]
比如弹起来后直接显示表情选择的面板。

版本：1.3.3

**Comment by Alexxiaopang** [comment]
我帮作者回复一下，可以模拟点击，如表情面板：  emotionBtn.performClick();

**Comment by YummyLau** [comment]
@Alexxiaopang 谢谢哈，这个方法是可以的。 @tt905 如果你用的是新版，有一个可以toPanel的方法，在toPanelState 也可以用
