### ISSUE TITLE
fragment初始化报错

### ISSUE THREAD

**Issue by lannaican** [YummyLau/PanelSwitchHelper#78]
1.3.5版本出现的
原先在1.3.4版本中正常使用
按照Demo在onActivityCreated中初始化也是一样报错
错误信息：lateinit property window has not been initialized

**Comment by YummyLau** [comment]
@lannaican demo正常否，这个是初始化window的api。贴个完整的log下。

**Comment by lannaican** [comment]
> @lannaican demo正常否，这个是初始化window的api。贴个完整的log下。

Demo还没下，我试下

**Comment by lannaican** [comment]
Demo是没问题的，对比了一下区别应该是搭配了ViewPager使用
这是错误信息
![{15C3426C-AE36-49AB-A477-59E24AB4186E}_20200720195629](https://user-images.githubusercontent.com/25725610/87935423-ae4df700-cac3-11ea-8b59-62278fe422e7.jpg)

**Comment by lannaican** [comment]
![{15C3426C-AE36-49AB-A477-59E24AB4186E}_20200720195629](https://user-images.githubusercontent.com/25725610/87935473-c4f44e00-cac3-11ea-84b1-21ee15a5330f.jpg)

**Comment by lannaican** [comment]
图片好像看不了。。

**Comment by YummyLau** [comment]
@lannaican ok,大致知道原因了。

**Comment by YummyLau** [comment]
@lannaican 用一下1.3.6

**Comment by lannaican** [comment]
> @lannaican 用一下1.3.6

可以了，谢谢
