### ISSUE TITLE
聊天背景上移

### ISSUE THREAD

**Issue by xchdong** [YummyLau/PanelSwitchHelper#79]
PanelSwitchLayout.bindWindow设置了window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_STATE_ALWAYS_HIDDEN or WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE)。外层设置的聊天背景，在软键盘显示的情况下也会上移。应该怎么解决？

**Comment by YummyLau** [comment]
可以在Container内写一个设置背景，然后固定高度不滑动。或者在外层写一个view设置背景，固定高度就不会滑动。方案有很多的，总有一种适合你。

**Comment by xchdong** [comment]
在提供的项目里面试了一下，背景也是会上移的。
文件名：activity_api_content_relative_layout.xml
变动代码如下，
<RelativeLayout
        android:id="@+id/root_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical">
        <TextView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:gravity="center"
            android:text="测试"
            android:textSize="20sp" />
    </RelativeLayout>

新增一个TextView模拟背景。
显示表情不会引起背景上移。唤起输入法，背景会上移。

**Comment by xchdong** [comment]
使用的版本，com.effective.android:panelSwitchHelper-androidx:1.3.2.1

**Comment by YummyLau** [comment]
@xchdong 升级下1.3.6。  新版本可以用scroll距离你返回0就可以了。另外，如果按照你现在的方案，TextView 不能写matchParent，应该测量到高度之后固定高度。matchParent会动态调整。

**Comment by xchdong** [comment]
好的。我升级版本试一下

**Comment by xchdong** [comment]
升级到1.3.6可以解决问题，感谢支持。
又遇到一个问题，需要大佬帮忙。
表情面板有一个删除按钮。点击删除按钮，怎么样删除整个表情？

**Comment by YummyLau** [comment]
可以参考 EmotionView#onItemClick，插入的时候，Emoji插入的是一张图片。删除的时候，你监听Edittext的删除，然后也是一个整体删除就好。如果你业务有做过映射，更应该这样处理了。
