### ISSUE TITLE
当列表数据较多的时候，切换软键盘的状态，列表数据会有闪动（不是按整体下滑，而是先显示上一部分，在下滑下一部分）,详情可见下图视频，下载了demo也会出现该情景

### ISSUE THREAD

**Issue by smileToWxm** [YummyLau/PanelSwitchHelper#80]
[Screenrecorder-2020-07-30-16-52-47-929.mp4.zip](https://github.com/YummyLau/PanelSwitchHelper/files/5000211/Screenrecorder-2020-07-30-16-52-47-929.mp4.zip)

**Comment by smileToWxm** [comment]
Screenrecorder-2020-07-30-16-52-47-929.mp4

**Comment by YummyLau** [comment]
@smileToWxm 看不到你的文件。

**Comment by YummyLau** [comment]
@smileToWxm 看起来你不是整体向上滑动，你关闭了滑动模式吗？ 或者滑动距离计算有误。

**Comment by smileToWxm** [comment]
> @smileToWxm 看起来你不是整体向上滑动，你关闭了滑动模式吗？ 或者滑动距离计算有误。

demo里面的也会，线性布局的页面，在你上滑列表，然后点击输入框有时候就会出现这种情况

**Comment by YummyLau** [comment]
@smileToWxm 我这里几个收集，demo都正常的。 会出现列表闪动的原因是可能列表被绘制了两次，而且高度发生了改变才会，滑动模式是没有高度更改的。
确认一下你的版本是，是否方便提供下你的helper初始化代码。

**Comment by smileToWxm** [comment]
这个视频中的版本是1.3.1， 手机是Android10，这个是从上面下载的demo
[Screenrecorder-2020-07-30-17-54-19-635.mp4.zip](https://github.com/YummyLau/PanelSwitchHelper/files/5000430/Screenrecorder-2020-07-30-17-54-19-635.mp4.zip)

**Comment by YummyLau** [comment]
@smileToWxm 1.3.1比较老了，你升级到最新版能解决这个问题了。
