### ISSUE TITLE
键盘消失会有之前面板ui闪烁

### ISSUE THREAD

**Issue by yyg20101** [YummyLau/PanelSwitchHelper#81]
Androidx版本：是
PanelSwitchHelper版本：v1.3.6
手机型号: vivo x20plus
手机系统版本： Android 8.1
问题描述：最新版demo中， 任意模式，点击左边+号，之后点击屏幕空白区域，再点击edittext键盘弹起，最后点击屏幕空白。会出现+号面板view闪烁消失
同理。。。。点击表情也会出现

**Comment by YummyLau** [comment]
@yyg20101 我这里的机型复现不出。 你上传下录制屏幕及贴下log下。

**Comment by yyg20101** [comment]
[Screenrecording_20200731_143604.zip](https://github.com/YummyLau/PanelSwitchHelper/files/5005515/Screenrecording_20200731_143604.zip)
视频查看，会有+号面板跟随键盘一起的过程

**Comment by YummyLau** [comment]
@yyg20101 这个是正常的。因为面板在输入下面，输入法只是改在面板上面而已。框架是支持调整动画速度的。你这个场景动画越慢越能看出来。你自己调整的，正是因为不同手机的软键盘隐藏速度有差异，才开放自定义速度控制。
