### ISSUE TITLE
在recyclerview外层加入刷新框架smartrefreshlayout，如果数据不足一页，打开软键盘，收起软键盘，页面会下移软键盘的高度，求解决

### ISSUE THREAD

**Issue by yzf570363518** [YummyLau/PanelSwitchHelper#83]

**Comment by yzf570363518** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:tools="http://schemas.android.com/tools"
    android:orientation="vertical"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:android="http://schemas.android.com/apk/res/android">









        <include layout="@layout/public_include_title_white"/>

        <com.effective.android.panel.view.PanelSwitchLayout
            android:id="@+id/panel_switch_layout"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical"
            app:animationSpeed="standard">

            
            
            
            <com.effective.android.panel.view.content.RelativeContentContainer
                android:id="@+id/content_view"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="vertical"
                app:relative_edit_view="@id/editText"
                tools:layout_height="500dp">

                <com.scwang.smartrefresh.layout.SmartRefreshLayout
                    android:id="@+id/refreshLayout"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    android:layout_marginBottom="50dp"
                    android:visibility="visible">

                    <cn.edu.app.parents.widget.panelSwitchHelper.HookActionUpRecyclerView
                        android:id="@+id/recyclerView"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:background="#f2f3f5"
                        android:tag="recyclerView"
                       />
                </com.scwang.smartrefresh.layout.SmartRefreshLayout>

                <TextView
                    android:visibility="gone"
                    android:id="@+id/tip_view_top"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:background="@android:color/holo_blue_bright"
                    android:gravity="center"
                    android:padding="10dp"
                    android:tag="tip_view_top"
                    android:layout_marginTop="100dp"
                    android:text="干预滑动，偏顶部布局滑动时不被其滑走"
                    android:textColor="@android:color/white"
                    android:layout_alignParentRight="true"
                    android:textSize="15sp"
                    android:textStyle="bold"
                    android:typeface="sans" />

                <TextView
                    android:visibility="gone"
                    android:id="@+id/tip_view"
                    android:layout_width="wrap_content"
                    android:layout_marginRight="100dp"
                    android:layout_height="wrap_content"
                    android:background="@android:color/holo_blue_bright"
                    android:gravity="center"
                    android:padding="10dp"
                    android:layout_marginTop="200dp"
                    android:text="不做干预，默认 ContentContainer 内的布局会随面板展开而滑动"
                    android:textColor="@android:color/white"
                    android:textSize="15sp"
                    android:textStyle="bold"
                    android:typeface="sans" />

                <TextView
                    android:visibility="gone"
                    android:id="@+id/tip_view_bottom"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:background="@android:color/holo_blue_bright"
                    android:gravity="center"
                    android:padding="10dp"
                    android:tag="tip_view_bottom"
                    android:layout_above="@+id/bottom_action"
                    android:layout_alignParentRight="true"
                    android:layout_marginBottom="100dp"
                    android:text="干预滑动，偏底部布局滑动时让其不被盖住"
                    android:textColor="@android:color/white"
                    android:textSize="15sp"
                    android:textStyle="bold"
                    android:typeface="sans" />

                <LinearLayout
                    android:id="@+id/bottom_action"
                    android:layout_width="match_parent"
                    android:layout_height="50dp"
                    android:layout_alignParentBottom="true"
                    android:background="@color/white"
                    android:gravity="center_vertical"
                    android:minHeight="50dp"
                    android:orientation="horizontal"
                    android:paddingLeft="@dimen/dp_10"
                    android:paddingRight="@dimen/dp_10">

                    
                    <ImageView
                        android:id="@+id/addBtn"
                        android:layout_width="35dp"
                        android:layout_height="35dp"
                        android:layout_marginRight="@dimen/dp_10"
                        android:src="@drawable/icon_add"
                        android:visibility="gone"/>

                    
                    <EditText
                        android:id="@+id/editText"
                        android:layout_width="0dp"
                        android:layout_height="30dp"
                        android:layout_weight="1"
                        android:layout_gravity="center"
                        android:layout_marginRight="10dp"
                        android:background="@drawable/shape_ffffff_in_bbbbbb_out_big"
                        android:layout_toLeftOf="@+id/iv_private_chat_send"
                        android:layout_centerVertical="true"
                        android:hint="输入新消息"
                        android:singleLine="true"
                        android:paddingLeft="16dp"
                        android:paddingRight="16dp"
                        android:textColor="@color/black"
                        android:textColorHint="#bbbbbd"
                        android:imeOptions="actionSend"
                        android:textSize="12sp" />

                    <LinearLayout
                        android:layout_width="wrap_content"
                        android:layout_height="35dp"
                        android:orientation="horizontal"
                        android:gravity="center_vertical">

                        
                        <ImageView
                            android:id="@+id/emotionBtn"
                            android:layout_width="20dp"
                            android:layout_height="20dp"
                            android:layout_marginEnd="@dimen/dp_10"
                            android:layout_marginRight="@dimen/dp_10"
                            android:src="@drawable/selector_emotion_btn"
                            android:visibility="gone"/>

                        <TextView
                            android:id="@+id/tvSend"
                            android:layout_width="60dp"
                            android:layout_height="25dp"
                            android:background="@drawable/shape_button_blue_cornor_small"
                            android:gravity="center"
                            android:text="发送"
                            android:textColor="@color/white"
                            android:textSize="15sp" />
                    </LinearLayout>

                </LinearLayout>

            </com.effective.android.panel.view.content.RelativeContentContainer>


            
            <com.effective.android.panel.view.panel.PanelContainer
                android:id="@+id/panel_container"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:background="#ebebeb"
                tools:layout_height="0dp"
                tools:layout_weight="1">

                
                
                
                
                <com.effective.android.panel.view.panel.PanelView
                    android:id="@+id/panel_emotion"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent"
                    app:panel_layout="@layout/panel_emotion_layout"
                    app:panel_trigger="@id/emotionBtn" />

                <com.effective.android.panel.view.panel.PanelView
                    android:id="@+id/panel_addition"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    app:panel_layout="@layout/panel_add_layout"
                    app:panel_trigger="@id/addBtn" />

            </com.effective.android.panel.view.panel.PanelContainer>
        </com.effective.android.panel.view.PanelSwitchLayout>

</LinearLayout>`

**Comment by yzf570363518** [comment]
![511596436685_ pic_hd](https://user-images.githubusercontent.com/11472179/89154446-75208700-d599-11ea-9cab-50e04fda401d.jpg)
![521596436693_ pic_hd](https://user-images.githubusercontent.com/11472179/89154468-849fd000-d599-11ea-9ce5-5ca738db2c88.jpg)
![531596436704_ pic_hd](https://user-images.githubusercontent.com/11472179/89154517-9bdebd80-d599-11ea-9555-52204f08fb04.jpg)
手机就普通的小米MIX2

**Comment by yzf570363518** [comment]
呼救作者，就我一个bug了，快快解答

**Comment by yzf570363518** [comment]
还有个bug，我滑动到上面好几页，打开软键盘，隐藏软键盘，会自动滚动到最后一行，救命啊

**Comment by yzf570363518** [comment]
![image](https://user-images.githubusercontent.com/11472179/89245100-abfaa980-d63a-11ea-9460-3359550175c9.png)
改好了

**Comment by YummyLau** [comment]
嗯嗯，理解scrollMeasurer的内部原理，就可以解决了。
你的滑动应该控制的时refreshLayout

**Comment by JD-CP** [comment]
> `
> ```
>     <include layout="@layout/public_include_title_white"/>
> 
>     <com.effective.android.panel.view.PanelSwitchLayout
>         android:id="@+id/panel_switch_layout"
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         android:orientation="vertical"
>         app:animationSpeed="standard">
> 
>         
>         
>         
>         <com.effective.android.panel.view.content.RelativeContentContainer
>             android:id="@+id/content_view"
>             android:layout_width="match_parent"
>             android:layout_height="match_parent"
>             android:orientation="vertical"
>             app:relative_edit_view="@id/editText"
>             tools:layout_height="500dp">
> 
>             <com.scwang.smartrefresh.layout.SmartRefreshLayout
>                 android:id="@+id/refreshLayout"
>                 android:layout_width="match_parent"
>                 android:layout_height="match_parent"
>                 android:layout_marginBottom="50dp"
>                 android:visibility="visible">
> 
>                 <cn.edu.app.parents.widget.panelSwitchHelper.HookActionUpRecyclerView
>                     android:id="@+id/recyclerView"
>                     android:layout_width="match_parent"
>                     android:layout_height="match_parent"
>                     android:background="#f2f3f5"
>                     android:tag="recyclerView"
>                    />
>             </com.scwang.smartrefresh.layout.SmartRefreshLayout>
> 
>             <TextView
>                 android:visibility="gone"
>                 android:id="@+id/tip_view_top"
>                 android:layout_width="wrap_content"
>                 android:layout_height="wrap_content"
>                 android:background="@android:color/holo_blue_bright"
>                 android:gravity="center"
>                 android:padding="10dp"
>                 android:tag="tip_view_top"
>                 android:layout_marginTop="100dp"
>                 android:text="干预滑动，偏顶部布局滑动时不被其滑走"
>                 android:textColor="@android:color/white"
>                 android:layout_alignParentRight="true"
>                 android:textSize="15sp"
>                 android:textStyle="bold"
>                 android:typeface="sans" />
> 
>             <TextView
>                 android:visibility="gone"
>                 android:id="@+id/tip_view"
>                 android:layout_width="wrap_content"
>                 android:layout_marginRight="100dp"
>                 android:layout_height="wrap_content"
>                 android:background="@android:color/holo_blue_bright"
>                 android:gravity="center"
>                 android:padding="10dp"
>                 android:layout_marginTop="200dp"
>                 android:text="不做干预，默认 ContentContainer 内的布局会随面板展开而滑动"
>                 android:textColor="@android:color/white"
>                 android:textSize="15sp"
>                 android:textStyle="bold"
>                 android:typeface="sans" />
> 
>             <TextView
>                 android:visibility="gone"
>                 android:id="@+id/tip_view_bottom"
>                 android:layout_width="wrap_content"
>                 android:layout_height="wrap_content"
>                 android:background="@android:color/holo_blue_bright"
>                 android:gravity="center"
>                 android:padding="10dp"
>                 android:tag="tip_view_bottom"
>                 android:layout_above="@+id/bottom_action"
>                 android:layout_alignParentRight="true"
>                 android:layout_marginBottom="100dp"
>                 android:text="干预滑动，偏底部布局滑动时让其不被盖住"
>                 android:textColor="@android:color/white"
>                 android:textSize="15sp"
>                 android:textStyle="bold"
>                 android:typeface="sans" />
> 
>             <LinearLayout
>                 android:id="@+id/bottom_action"
>                 android:layout_width="match_parent"
>                 android:layout_height="50dp"
>                 android:layout_alignParentBottom="true"
>                 android:background="@color/white"
>                 android:gravity="center_vertical"
>                 android:minHeight="50dp"
>                 android:orientation="horizontal"
>                 android:paddingLeft="@dimen/dp_10"
>                 android:paddingRight="@dimen/dp_10">
> 
>                 
>                 <ImageView
>                     android:id="@+id/addBtn"
>                     android:layout_width="35dp"
>                     android:layout_height="35dp"
>                     android:layout_marginRight="@dimen/dp_10"
>                     android:src="@drawable/icon_add"
>                     android:visibility="gone"/>
> 
>                 
>                 <EditText
>                     android:id="@+id/editText"
>                     android:layout_width="0dp"
>                     android:layout_height="30dp"
>                     android:layout_weight="1"
>                     android:layout_gravity="center"
>                     android:layout_marginRight="10dp"
>                     android:background="@drawable/shape_ffffff_in_bbbbbb_out_big"
>                     android:layout_toLeftOf="@+id/iv_private_chat_send"
>                     android:layout_centerVertical="true"
>                     android:hint="输入新消息"
>                     android:singleLine="true"
>                     android:paddingLeft="16dp"
>                     android:paddingRight="16dp"
>                     android:textColor="@color/black"
>                     android:textColorHint="#bbbbbd"
>                     android:imeOptions="actionSend"
>                     android:textSize="12sp" />
> 
>                 <LinearLayout
>                     android:layout_width="wrap_content"
>                     android:layout_height="35dp"
>                     android:orientation="horizontal"
>                     android:gravity="center_vertical">
> 
>                     
>                     <ImageView
>                         android:id="@+id/emotionBtn"
>                         android:layout_width="20dp"
>                         android:layout_height="20dp"
>                         android:layout_marginEnd="@dimen/dp_10"
>                         android:layout_marginRight="@dimen/dp_10"
>                         android:src="@drawable/selector_emotion_btn"
>                         android:visibility="gone"/>
> 
>                     <TextView
>                         android:id="@+id/tvSend"
>                         android:layout_width="60dp"
>                         android:layout_height="25dp"
>                         android:background="@drawable/shape_button_blue_cornor_small"
>                         android:gravity="center"
>                         android:text="发送"
>                         android:textColor="@color/white"
>                         android:textSize="15sp" />
>                 </LinearLayout>
> 
>             </LinearLayout>
> 
>         </com.effective.android.panel.view.content.RelativeContentContainer>
> 
> 
>         
>         <com.effective.android.panel.view.panel.PanelContainer
>             android:id="@+id/panel_container"
>             android:layout_width="match_parent"
>             android:layout_height="wrap_content"
>             android:background="#ebebeb"
>             tools:layout_height="0dp"
>             tools:layout_weight="1">
> 
>             
>             
>             
>             
>             <com.effective.android.panel.view.panel.PanelView
>                 android:id="@+id/panel_emotion"
>                 android:layout_width="match_parent"
>                 android:layout_height="match_parent"
>                 app:panel_layout="@layout/panel_emotion_layout"
>                 app:panel_trigger="@id/emotionBtn" />
> 
>             <com.effective.android.panel.view.panel.PanelView
>                 android:id="@+id/panel_addition"
>                 android:layout_width="match_parent"
>                 android:layout_height="wrap_content"
>                 app:panel_layout="@layout/panel_add_layout"
>                 app:panel_trigger="@id/addBtn" />
> 
>         </com.effective.android.panel.view.panel.PanelContainer>
>     </com.effective.android.panel.view.PanelSwitchLayout>
> ```
> 
> `

RelativeContentContainer嵌套SmartRefreshLayout，在下拉刷新上拉加载时，有遇到滑动冲突的问题吗？
