### ISSUE TITLE
如果聊天列表内容过少会导致recyclerview整体上移

### ISSUE THREAD

**Issue by yyg20101** [YummyLau/PanelSwitchHelper#84]
如题，如果recyclerview的内容过少，面板弹起会导致recyclerview整体上移

**Comment by YummyLau** [comment]
@yyg20101 有api可以控制，参考demo及文档哦

**Comment by baiyuliang** [comment]
> @yyg20101 有api可以控制，参考demo及文档哦

能直接把解决代码贴出来吗，网不行，下载源码一直失败
