### ISSUE TITLE
切换全屏与非全屏会导致布局错乱

### ISSUE THREAD

**Issue by lannaican** [YummyLau/PanelSwitchHelper#85]
全屏的方法：window.addFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN);
添加之后弹出输入法会导致布局整体上移，软键盘弹出的高度也不正确。
我想实现的类似B站视频播放页面，状态栏随播放器控制器显示和隐藏

**Comment by YummyLau** [comment]
demo中B站横屏全屏场景也是全屏，如果是竖屏全屏则不能，这是 FLAG_FULLSCREEN 对adjustResize 会失效的影响以及使用dialog等window在横屏全屏的考虑。
每一个细小的系统栏变化都会引起很大的设计差异，demo的b站的设计是按照b站视频播放的交互，竖屏状态栏可见，横屏状态栏不可见，可参考demo。
如果需要控制动态隐藏，应该了解 SYSTEM_UI_FLAG_LAYOUT_STABLE及 SYSTEM_UI_FLAG_IMMERSIVE_STICKY 控制动态隐藏/显示系统烂对你业务设计的影响，这些flag的使用对全屏的更改前提下使用PanelSwitchHelper。
另外不同系统的flag的表现可能不同，应该充分了解并针对不同版本的系统使用不同的flag来控制window的表现。

**Comment by lannaican** [comment]
好的谢谢
