### ISSUE TITLE
面板和键盘的切换是否做了防抖动机制？

### ISSUE THREAD

**Issue by VeerHan** [YummyLau/PanelSwitchHelper#88]
如demo所示，快速点击表情按钮，键盘和表情面板不能快速切换。是否可以对外提供开关防抖动的接口。

**Comment by YummyLau** [comment]
内部做了保护，因为软键盘弹起需要一定的时间。提供防抖指的是什么呢

**Comment by VeerHan** [comment]
> 内部做了保护，因为软键盘弹起需要一定的时间。提供防抖指的是什么呢 你是希望关闭这个保护吗？

是的，我希望关闭这个保护。请问在哪里修改？

**Comment by YummyLau** [comment]
@VeerHan 暂时不开放的，因为软键盘/layout过渡动画都需要时间，如果随意打断容易出现不可预知的bug。代码在 PanelSwitchLayout#initListener，你可以fork/clone进行单独修改。

**Comment by VeerHan** [comment]
好的，多谢

**Comment by VeerHan** [comment]
> @VeerHan 暂时不开放的，因为软键盘/layout过渡动画都需要时间，如果随意打断容易出现不可预知的bug。代码在 PanelSwitchLayout#initListener，你可以fork/clone进行单独修改。

建议提供api修改过渡动画的时间。
我现在直接在源码改的时间，每次升级新版本都要手动把源码导入进来并再次手动修改时间，有点麻烦。
