### ISSUE TITLE
ViewPager Fragment出现异常

### ISSUE THREAD

**Issue by dongliwu520** [YummyLau/PanelSwitchHelper#93]
在使用ViewPager+Fragment组合时, 每次会预加载下一个页面.
第一个Fragment打开面板显示和使用都正常, 后面的所有Fragment中的面板都无法正常使用
情况如下：弹起面板时onPanelSizeChange回调方法确定都正常执行  里面关于UI和数据的代码也确定都执行了  但是界面却无法加载任何数据   只显示的xml里的初始UI    包括添加的点击事件都无法执行

@Override
                    public void onPanelSizeChange(IPanelView iPanelView, boolean b, int i, int i1, int i2, int i3) {
                        if (((PanelView) iPanelView).getId() == R.id.panel_emotion) {
                            // 整理表情按钮
                            btnEmoJiManager = getRootView().findViewById(R.id.btnEmoJiManager);
                            // 表情列表
                            rvEmoJi = getRootView().findViewById(R.id.rvEmoJi);
                            // 跳转到整理表情页面
                            btnEmoJiManager.setOnClickListener(v -> {
                                if (mListener != null) mListener.onClearUpEmoJiClick();
                            });
                            // 初始化面板列表和适配器
                            settingEmoJiPanel();
                            stickerAdapter = ViewUtil.initEmoJiRecyclerView(getContext(), rvEmoJi, stickerAdapter, stickers);
                            stickerAdapter.setEmoJiState(1);
                            stickerAdapter.setOnItemChildClickListener(ActivitiesDetailView.this);
                        }
                    }
                })

**Comment by dongliwu520** [comment]
另外, 能否在进页面时就初始面板里的UI?  而不是回调到onPanelSizeChange再去初始化呢?

**Comment by mengyuqiang** [comment]
请问后续怎么解决的呢？我的也是ViewPager2+Fragment切换，一旦某个Fragment弹起键盘，后面的几个Fragment中的PanelSwitchLayout中的按钮、数据都不显示了
