### ISSUE TITLE
Dialog布局中填充布局高度不确定时，window高度和布局状态异常

### ISSUE THREAD

**Issue by woilsy** [YummyLau/PanelSwitchHelper#94]
Androidx版本：是
PanelSwitchHelper版本：v1.3.8
手机型号: 任何机型
手机系统版本： Android 5.0+
问题描述：Demo中的dialog场景下，只需要修改common_chat_with_titlebar_layout.xml中的布局，如id为title_bar的RelativeLayout高度为0dp，layout_weight为0.2(或其他值)即可复现。RelativeLayout会在键盘弹起时压缩，且键盘弹起时会先显示部分panel内容然后又下移的一个动画，而关闭键盘时，panel又会先升起一段距离再收回。收回有时候panel那部分甚至会显示在屏幕底部下方，点击屏幕后又回到屏幕底部。这个问题目前除了给RelativeLayout为固定高度以外，没有其他解决办法.

**Comment by YummyLau** [comment]
@woilsy 不建议使用动态高度，因为layout的再次调整及动画在时间上可能又冲突，性能也有一定损耗

**Comment by woilsy** [comment]
有时候业务需求上要求按照窗体百分比展示dialog，空白那部分需要动态计算，但是这个框架的测量流程应该是在inflate之后，onMeasure之前，导致没办法控制这个高度，也就是说除了高度写死没有任何方式，但是android开发中又要适配，很无解。

**Comment by YummyLau** [comment]
> 有时候业务需求上要求按照窗体百分比展示dialog，空白那部分需要动态计算，但是这个框架的测量流程应该是在inflate之后，onMeasure之前，导致没办法控制这个高度，也就是说除了高度写死没有任何方式，但是android开发中又要适配，很无解。

不对，测量值是在onLayout前，你有机会干预。
