### ISSUE TITLE
直播场景修改recyclerview位置后出现异常

### ISSUE THREAD

**Issue by stopWang** [YummyLau/PanelSwitchHelper#96]
我将activity_douyin_live_layout.xml中recyclerview的位置设置修改了一下 出现效果如图 弹出软键盘后recyclerview顶起了很高

      <com.example.demo.scene.chat.view.HookActionUpRecyclerView
                    android:id="@+id/comment_list"
                    android:layout_width="300dp"
                    android:layout_height="350dp"
                    android:layout_marginLeft="5dp"
                    android:padding="5dp"
                    android:layout_above="@+id/action_show_layout"
                    android:layout_marginBottom="50dp" />
![聊天弹出bug](https://user-images.githubusercontent.com/19582091/93051599-5bde2080-f697-11ea-8757-75ae015f35f2.png)

**Comment by YummyLau** [comment]
@stopWang 请参考demo中如何自定义控制滑动布局api。可以自主控制，默认是向上滑动一个输入法高度。
