### ISSUE TITLE
软键盘无法收回

### ISSUE THREAD

**Issue by lannaican** [YummyLau/PanelSwitchHelper#98]
Androidx版本：是
PanelSwitchHelper版本：v1.3.9-v1.3.10-beta
手机系统版本： Android 9.0以下
问题描述：在1.3.9以上版本在Andorid 8以及以下系统会出现键盘无法关闭的情况，即收回软键盘又会马上弹出，我切换到1.3.8即正常。

**Comment by lannaican** [comment]
以下是点击返回键收起软键盘到软键盘又自动弹出的日志：
I: Begin update info ...
I: Update info took 1 ms
    
    --------- beginning of system
D: PanelSwitchLayout(34345546)#onLayout =>  getCompatPanelHeight  :499
D: PanelSwitchLayout(34345546)#onLayout =>  getContentContainerTop  :0
D: PanelSwitchLayout(34345546)#onLayout =>  onLayout(changed : true , l : 0  , t : 98 , r : 768 , b : 1136） ===================&&&&=================
D: PanelSwitchLayout(34345546)#onLayout =>  当前状态  :显示键盘输入
D: PanelSwitchLayout(34345546)#onLayout =>  是否是全屏  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否是pad机型  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否显示导航栏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  是否是竖屏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（包含系统UI）  ：1280
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1184
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，动态计算）  ：1136
D: PanelSwitchLayout(34345546)#onLayout =>  localLocation[y]  ：146
D: PanelSwitchLayout(34345546)#onLayout =>  toolbar高度  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  StatusBar高度  ：48
D: PanelSwitchLayout(34345546)#onLayout =>  NavigationBar高度  ：95
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，146）
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout paddingTop  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  输入法高度  ：499
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 top  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 高度 ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 top ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 高度 499
D: PanelSwitchLayout(34345546)#onLayout =>  changeBounds : false
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer : height - 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 768 b : 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainerTop : height - 499
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainer :  l : 0  : 540 r : 768 b : 1039
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  window softInputMode (19)
D: PanelSwitchLayout(34345546)#onGlobalLayout => 容器是否可见(true)
D: PanelSwitchLayout(34345546)#onGlobalLayout => screenHeight is : 1280
D: PanelSwitchLayout(34345546)#onGlobalLayout => contentHeight is : 1136
D: PanelSwitchLayout(34345546)#onGlobalLayout => isFullScreen (false)
D: PanelSwitchLayout(34345546)#onGlobalLayout => navigationBarShown is : true
D: PanelSwitchLayout(34345546)#onGlobalLayout => 设备 statusBarH : 48，navigationBarH : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => 当前界面 statusBarH : 48, navigationBarH : 95 全面屏手势虚拟栏H : 0
D: PanelSwitchLayout(34345546)#onGlobalLayout => SystemUI's H :  143
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitCloseKeyboardHeight  : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitOpenKeyboardHeight  : 300
D: PanelSwitchLayout(34345546)#onGlobalLayout => lastKeyboardHeight  : 499
D: PanelSwitchLayout(34345546)#onGlobalLayout => keyboardH : 1, realKeyboardH : 1, isShown : true
D: OnEditFocusChangeListener#onFocusChange => EditText has focus ( true )
D: PanelSwitchLayout(34345546)#checkoutPanel => is checkouting,just ignore!
D: PanelSwitchLayout(34345546)#checkoutPanel => checkout success ! lastPanel's id : 0 , panel's id :-1
D: OnPanelChangeListener#onNone => panel： none
D: OnKeyboardStateListener#onKeyboardChange => Keyboard is showing ( false ),height is 0
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#onLayout =>  getCompatPanelHeight  :499
D: PanelSwitchLayout(34345546)#onLayout =>  getContentContainerTop  :0
D: PanelSwitchLayout(34345546)#onLayout =>  onLayout(changed : false , l : 0  , t : 98 , r : 768 , b : 1136） ===================&&&&=================
D: PanelSwitchLayout(34345546)#onLayout =>  当前状态  :收起所有输入源
D: PanelSwitchLayout(34345546)#onLayout =>  是否是全屏  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否是pad机型  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否显示导航栏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  是否是竖屏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（包含系统UI）  ：1280
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1184
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，动态计算）  ：1136
D: PanelSwitchLayout(34345546)#onLayout =>  localLocation[y]  ：146
D: PanelSwitchLayout(34345546)#onLayout =>  toolbar高度  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  StatusBar高度  ：48
D: PanelSwitchLayout(34345546)#onLayout =>  NavigationBar高度  ：95
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，146）
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout paddingTop  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  输入法高度  ：499
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 top  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 高度 ：1039
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 top ：1039
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 高度 499
D: PanelSwitchLayout(34345546)#onLayout =>  changeBounds : true
D: PanelSwitchLayout(34345546)#onLayout =>  reverseResetState : true
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer : height - 1039
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 768 b : 1039
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainerTop : height - 499
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainer :  l : 0  : 1039 r : 768 b : 1538
D: OnEditFocusChangeListener#onFocusChange => EditText has focus ( true )
D: OnEditFocusChangeListener#onFocusChange => EditText has focus ( true )
D: PanelSwitchLayout(34345546)#checkoutPanel => is checkouting,just ignore!
D: PanelSwitchLayout(34345546)#checkoutPanel => checkout success ! lastPanel's id : -1 , panel's id :0
D: OnPanelChangeListener#onKeyboard => panel： keyboard
W: requestLayout() improperly called by com.effective.android.panel.view.content.LinearContentContainer{c41b575 V.E...... ......ID 0,0-768,1039} during layout: running second layout pass
D: PanelSwitchLayout(34345546)#onLayout =>  getCompatPanelHeight  :499
D: PanelSwitchLayout(34345546)#onLayout =>  getContentContainerTop  :0
D: PanelSwitchLayout(34345546)#onLayout =>  onLayout(changed : false , l : 0  , t : 98 , r : 768 , b : 1136） ===================&&&&=================
D: PanelSwitchLayout(34345546)#onLayout =>  当前状态  :显示键盘输入
D: PanelSwitchLayout(34345546)#onLayout =>  是否是全屏  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否是pad机型  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否显示导航栏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  是否是竖屏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（包含系统UI）  ：1280
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1184
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，动态计算）  ：1136
D: PanelSwitchLayout(34345546)#onLayout =>  localLocation[y]  ：146
D: PanelSwitchLayout(34345546)#onLayout =>  toolbar高度  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  StatusBar高度  ：48
D: PanelSwitchLayout(34345546)#onLayout =>  NavigationBar高度  ：95
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，146）
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout paddingTop  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  输入法高度  ：499
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 top  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 高度 ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 top ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 高度 499
D: PanelSwitchLayout(34345546)#onLayout =>  changeBounds : true
D: PanelSwitchLayout(34345546)#onLayout =>  reverseResetState : true
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer : height - 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 768 b : 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainerTop : height - 499
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainer :  l : 0  : 540 r : 768 b : 1039
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  window softInputMode (19)
D: PanelSwitchLayout(34345546)#onGlobalLayout => 容器是否可见(true)
D: PanelSwitchLayout(34345546)#onGlobalLayout => screenHeight is : 1280
D: PanelSwitchLayout(34345546)#onGlobalLayout => contentHeight is : 1136
D: PanelSwitchLayout(34345546)#onGlobalLayout => isFullScreen (false)
D: PanelSwitchLayout(34345546)#onGlobalLayout => navigationBarShown is : true
D: PanelSwitchLayout(34345546)#onGlobalLayout => 设备 statusBarH : 48，navigationBarH : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => 当前界面 statusBarH : 48, navigationBarH : 95 全面屏手势虚拟栏H : 0
D: PanelSwitchLayout(34345546)#onGlobalLayout => SystemUI's H :  143
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitCloseKeyboardHeight  : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitOpenKeyboardHeight  : 300
D: PanelSwitchLayout(34345546)#onGlobalLayout => lastKeyboardHeight  : 1
D: PanelSwitchLayout(34345546)#onGlobalLayout => keyboardH : 1, realKeyboardH : 1, isShown : false
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
W: beginBatchEdit on inactive InputConnection
W: getTextBeforeCursor on inactive InputConnection
W: requestLayout() improperly called by com.effective.android.panel.view.PanelSwitchLayout{20c124a V.E...... .......D 0,98-768,1136} during second layout pass: posting in next frame
W: requestLayout() improperly called by com.effective.android.panel.view.content.LinearContentContainer{c41b575 V.E...... ......ID 0,0-768,540} during second layout pass: posting in next frame
D: PanelSwitchLayout(34345546)#onLayout =>  getCompatPanelHeight  :499
D: PanelSwitchLayout(34345546)#onLayout =>  getContentContainerTop  :0
D: PanelSwitchLayout(34345546)#onLayout =>  onLayout(changed : false , l : 0  , t : 98 , r : 768 , b : 1136） ===================&&&&=================
D: PanelSwitchLayout(34345546)#onLayout =>  当前状态  :显示键盘输入
D: PanelSwitchLayout(34345546)#onLayout =>  是否是全屏  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否是pad机型  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否显示导航栏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  是否是竖屏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（包含系统UI）  ：1280
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1184
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，动态计算）  ：1136
D: PanelSwitchLayout(34345546)#onLayout =>  localLocation[y]  ：146
D: PanelSwitchLayout(34345546)#onLayout =>  toolbar高度  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  StatusBar高度  ：48
D: PanelSwitchLayout(34345546)#onLayout =>  NavigationBar高度  ：95
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，146）
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout paddingTop  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  输入法高度  ：499
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 top  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 高度 ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 top ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 高度 499
D: PanelSwitchLayout(34345546)#onLayout =>  changeBounds : false
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer : height - 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 768 b : 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainerTop : height - 499
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainer :  l : 0  : 540 r : 768 b : 1039
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  window softInputMode (19)
D: PanelSwitchLayout(34345546)#onGlobalLayout => 容器是否可见(true)
D: PanelSwitchLayout(34345546)#onGlobalLayout => screenHeight is : 1280
D: PanelSwitchLayout(34345546)#onGlobalLayout => contentHeight is : 1136
D: PanelSwitchLayout(34345546)#onGlobalLayout => isFullScreen (false)
D: PanelSwitchLayout(34345546)#onGlobalLayout => navigationBarShown is : true
D: PanelSwitchLayout(34345546)#onGlobalLayout => 设备 statusBarH : 48，navigationBarH : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => 当前界面 statusBarH : 48, navigationBarH : 95 全面屏手势虚拟栏H : 0
D: PanelSwitchLayout(34345546)#onGlobalLayout => SystemUI's H :  143
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitCloseKeyboardHeight  : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitOpenKeyboardHeight  : 300
D: PanelSwitchLayout(34345546)#onGlobalLayout => lastKeyboardHeight  : 1
D: PanelSwitchLayout(34345546)#onGlobalLayout => keyboardH : 1, realKeyboardH : 1, isShown : false
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
W: getTextAfterCursor on inactive InputConnection
W: getSelectedText on inactive InputConnection
W: endBatchEdit on inactive InputConnection
W: beginBatchEdit on inactive InputConnection
W: getTextBeforeCursor on inactive InputConnection
W: getTextAfterCursor on inactive InputConnection
W: getSelectedText on inactive InputConnection
W: endBatchEdit on inactive InputConnection
W: beginBatchEdit on inactive InputConnection
W: getTextBeforeCursor on inactive InputConnection
W: getTextAfterCursor on inactive InputConnection
W: getSelectedText on inactive InputConnection
W: endBatchEdit on inactive InputConnection
W: beginBatchEdit on inactive InputConnection
W: getTextBeforeCursor on inactive InputConnection
W: getTextAfterCursor on inactive InputConnection
W: getSelectedText on inactive InputConnection
W: endBatchEdit on inactive InputConnection
D: PanelSwitchLayout(34345546)#onLayout =>  getCompatPanelHeight  :499
D: PanelSwitchLayout(34345546)#onLayout =>  getContentContainerTop  :0
D: PanelSwitchLayout(34345546)#onLayout =>  onLayout(changed : true , l : 0  , t : 98 , r : 768 , b : 638） ===================&&&&=================
D: PanelSwitchLayout(34345546)#onLayout =>  当前状态  :显示键盘输入
D: PanelSwitchLayout(34345546)#onLayout =>  是否是全屏  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否是pad机型  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否显示导航栏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  是否是竖屏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（包含系统UI）  ：1280
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1184
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，动态计算）  ：638
D: PanelSwitchLayout(34345546)#onLayout =>  localLocation[y]  ：146
D: PanelSwitchLayout(34345546)#onLayout =>  toolbar高度  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  StatusBar高度  ：48
D: PanelSwitchLayout(34345546)#onLayout =>  NavigationBar高度  ：95
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，146）
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout paddingTop  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  输入法高度  ：499
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 top  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 高度 ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 top ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 高度 499
D: PanelSwitchLayout(34345546)#onLayout =>  changeBounds : false
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer : height - 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 768 b : 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainerTop : height - 499
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainer :  l : 0  : 540 r : 768 b : 1039
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  window softInputMode (19)
D: PanelSwitchLayout(34345546)#onGlobalLayout => 容器是否可见(true)
D: PanelSwitchLayout(34345546)#onGlobalLayout => screenHeight is : 1280
D: PanelSwitchLayout(34345546)#onGlobalLayout => contentHeight is : 638
D: PanelSwitchLayout(34345546)#onGlobalLayout => isFullScreen (false)
D: PanelSwitchLayout(34345546)#onGlobalLayout => navigationBarShown is : true
D: PanelSwitchLayout(34345546)#onGlobalLayout => 设备 statusBarH : 48，navigationBarH : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => 当前界面 statusBarH : 48, navigationBarH : 95 全面屏手势虚拟栏H : 0
D: PanelSwitchLayout(34345546)#onGlobalLayout => SystemUI's H :  143
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitCloseKeyboardHeight  : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitOpenKeyboardHeight  : 300
D: PanelSwitchLayout(34345546)#onGlobalLayout => lastKeyboardHeight  : 1
D: PanelSwitchLayout(34345546)#onGlobalLayout => keyboardH : 499, realKeyboardH : 499, isShown : false
D: OnKeyboardStateListener#onKeyboardChange => Keyboard is showing ( true ),height is 499
D: PanelSwitchLayout(34345546)#onGlobalLayout => try to set KeyBoardHeight : 499，isShow true
D: PanelUtil#onGlobalLayout => current KeyBoardHeight is equal，just ignore！
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#onLayout =>  getCompatPanelHeight  :499
D: PanelSwitchLayout(34345546)#onLayout =>  getContentContainerTop  :0
D: PanelSwitchLayout(34345546)#onLayout =>  onLayout(changed : false , l : 0  , t : 98 , r : 768 , b : 638） ===================&&&&=================
D: PanelSwitchLayout(34345546)#onLayout =>  当前状态  :显示键盘输入
D: PanelSwitchLayout(34345546)#onLayout =>  是否是全屏  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否是pad机型  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否显示导航栏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  是否是竖屏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（包含系统UI）  ：1280
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1184
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，动态计算）  ：638
D: PanelSwitchLayout(34345546)#onLayout =>  localLocation[y]  ：146
D: PanelSwitchLayout(34345546)#onLayout =>  toolbar高度  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  StatusBar高度  ：48
D: PanelSwitchLayout(34345546)#onLayout =>  NavigationBar高度  ：95
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，146）
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout paddingTop  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  输入法高度  ：499
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 top  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 高度 ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 top ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 高度 499
D: PanelSwitchLayout(34345546)#onLayout =>  changeBounds : false
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer : height - 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 768 b : 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainerTop : height - 499
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainer :  l : 0  : 540 r : 768 b : 1039
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  window softInputMode (19)
D: PanelSwitchLayout(34345546)#onGlobalLayout => 容器是否可见(true)
D: PanelSwitchLayout(34345546)#onGlobalLayout => screenHeight is : 1280
D: PanelSwitchLayout(34345546)#onGlobalLayout => contentHeight is : 638
D: PanelSwitchLayout(34345546)#onGlobalLayout => isFullScreen (false)
D: PanelSwitchLayout(34345546)#onGlobalLayout => navigationBarShown is : true
D: PanelSwitchLayout(34345546)#onGlobalLayout => 设备 statusBarH : 48，navigationBarH : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => 当前界面 statusBarH : 48, navigationBarH : 95 全面屏手势虚拟栏H : 0
D: PanelSwitchLayout(34345546)#onGlobalLayout => SystemUI's H :  143
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitCloseKeyboardHeight  : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitOpenKeyboardHeight  : 300
D: PanelSwitchLayout(34345546)#onGlobalLayout => lastKeyboardHeight  : 499
D: PanelSwitchLayout(34345546)#onGlobalLayout => keyboardH : 499, realKeyboardH : 499, isShown : true
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#checkoutPanel => current panelId is 0 ,just ignore!
D: PanelSwitchLayout(34345546)#onLayout =>  getCompatPanelHeight  :499
D: PanelSwitchLayout(34345546)#onLayout =>  getContentContainerTop  :0
D: PanelSwitchLayout(34345546)#onLayout =>  onLayout(changed : false , l : 0  , t : 98 , r : 768 , b : 638） ===================&&&&=================
D: PanelSwitchLayout(34345546)#onLayout =>  当前状态  :显示键盘输入
D: PanelSwitchLayout(34345546)#onLayout =>  是否是全屏  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否是pad机型  ：false
D: PanelSwitchLayout(34345546)#onLayout =>  是否显示导航栏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  是否是竖屏  ：true
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（包含系统UI）  ：1280
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，无论导航栏显示与否）  ：1184
D: PanelSwitchLayout(34345546)#onLayout =>  界面高度（不包含系统UI，动态计算）  ：638
D: PanelSwitchLayout(34345546)#onLayout =>  localLocation[y]  ：146
D: PanelSwitchLayout(34345546)#onLayout =>  toolbar高度  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  StatusBar高度  ：48
D: PanelSwitchLayout(34345546)#onLayout =>  NavigationBar高度  ：95
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout 绘制起点  ：（0，146）
D: PanelSwitchLayout(34345546)#onLayout =>  PanelSwitchLayout paddingTop  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  输入法高度  ：499
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 top  ：0
D: PanelSwitchLayout(34345546)#onLayout =>  内容容器 高度 ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 top ：540
D: PanelSwitchLayout(34345546)#onLayout =>  面板容器 高度 499
D: PanelSwitchLayout(34345546)#onLayout =>  changeBounds : false
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer : height - 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 contentContainer :  l : 0 t : 0 r : 768 b : 540
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainerTop : height - 499
D: PanelSwitchLayout(34345546)#onLayout =>  layout参数 panelContainer :  l : 0  : 540 r : 768 b : 1039
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  
D: PanelSwitchLayout(34345546)#onGlobalLayout =>  window softInputMode (19)
D: PanelSwitchLayout(34345546)#onGlobalLayout => 容器是否可见(true)
D: PanelSwitchLayout(34345546)#onGlobalLayout => screenHeight is : 1280
D: PanelSwitchLayout(34345546)#onGlobalLayout => contentHeight is : 638
D: PanelSwitchLayout(34345546)#onGlobalLayout => isFullScreen (false)
D: PanelSwitchLayout(34345546)#onGlobalLayout => navigationBarShown is : true
D: PanelSwitchLayout(34345546)#onGlobalLayout => 设备 statusBarH : 48，navigationBarH : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => 当前界面 statusBarH : 48, navigationBarH : 95 全面屏手势虚拟栏H : 0
D: PanelSwitchLayout(34345546)#onGlobalLayout => SystemUI's H :  143
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitCloseKeyboardHeight  : 95
D: PanelSwitchLayout(34345546)#onGlobalLayout => minLimitOpenKeyboardHeight  : 300
D: PanelSwitchLayout(34345546)#onGlobalLayout => lastKeyboardHeight  : 499
D: PanelSwitchLayout(34345546)#onGlobalLayout => keyboardH : 499, realKeyboardH : 499, isShown : true
D: PanelSwitchLayout(34345546)#onGlobalLayout =>

**Comment by HuYueling** [comment]
我也遇到了这个问题
Androidx版本：是
PanelSwitchHelper版本：v1.3.10-beta
型号：小米5
系统版本： Android 8.0.0
问题描述：收回软键盘又会马上弹出

**Comment by YummyLau** [comment]
Container可以加一下 android:focusable = "true" 和 android:focusableTouchMode = "true"。这个问题是部分机型新版本会抢占焦点。已经修复了，后续更新。
