### ISSUE TITLE
如何使用recycleview绑定panelview

### ISSUE THREAD

**Issue by HuYueling** [YummyLau/PanelSwitchHelper#99]
PanelSwitchHelper版本：1.3.10-beta
问题描述：在使用的时候panelview需要绑定trigger，我使用的recycleview，改如何去绑定trigger

**Comment by YummyLau** [comment]
@HuYueling “我使用的recycleview，改如何去绑定trigger” 不太理解这句话的意思。你指的是recyclerview里面需要某些holder的view需要点击显示面板吗？

**Comment by HuYueling** [comment]
嗯嗯，是的，这样子panelview的trigger改填写哪个id

**Comment by YummyLau** [comment]
@HuYueling 想实时替换吗？不建议这样做。 这种场景比较特殊的。你可以在holder的view的Click实践去调用对应triggerView的perforClcik，做到功能同步同时triggerView状态也同步。

**Comment by HuYueling** [comment]
好的，我试试，感谢
